;;;
;;; Allen's Interval Algebra (AIA) with 13 base relations
;;;

(def-calculus "Allen's Interval Algebra (AIA IA)"
  :arity :binary
  :parametric? nil
  :consistency :scenario-consistency
  :qualifier #'(lambda (p1 p2)
		 (let ((s1 (first p1))
		       (e1 (second p1))
		       (s2 (first p2))
		       (e2 (second p2)))
		   (cond ((< s1 s2) (cond ((< e1 s2) 'B)
					  ((= e1 s2) 'M)
					  (t (cond ((< e1 e2) 'O)
						   ((= e1 e2) 'FI)
						   (t 'DI)))))
			 ((= s1 s2) (cond ((< e1 e2) 'S)
					  ((= e1 e2) 'EQ)
					  (t 'SI)))
			 (t (cond ((< e2 s1) 'BI)
				  ((= e2 s1) 'MI)
				  (t (cond ((< e2 e1) 'OI)
					   ((= e2 e1) 'F)
					   (t 'D))))))))

  :basis-entity :interval
  :identity-relation EQ
  :converse-operation ((EQ EQ)
		       (B  BI)
		       (BI B )
		       (D  DI)
		       (DI D )
		       (O  OI)
		       (OI O )
		       (M  MI)
		       (MI M )
		       (S  SI)
                       (SI S)
		       (F  FI)
		       (FI F ))
  
  :base-relations (EQ B BI D DI O OI M MI S SI F FI)
  :composition-operation ((EQ EQ	EQ)
			  (EQ B	        B)
			  (EQ BI	BI)
			  (EQ D		D)
			  (EQ DI	DI)
			  (EQ O		O)
			  (EQ OI	OI)
			  (EQ M		M)
			  (EQ MI	MI)
			  (EQ S		S)
			  (EQ SI	SI)
			  (EQ F		F)
			  (EQ FI	FI)
			  
			  (B  EQ	B)
			  (B  B		B)
			  (B  BI	(EQ B BI D DI O OI M MI S SI F FI))
			  (B  D		(B O M D S))
			  (B  DI	B)
			  (B  O		B)
			  (B  OI	(B O M D S))
			  (B  M		B)
			  (B  MI	(B O M D S))
			  (B  S		B)
			  (B  SI	B)
			  (B  F		(B O M D S))
			  (B  FI	B)
			  
			  (BI EQ	BI)
			  (BI B		(EQ B BI D DI O OI M MI S SI F FI))
			  (BI BI	BI)
			  (BI D		(BI OI MI D F))
			  (BI DI	BI)
			  (BI O		(BI OI MI D F))
			  (BI OI	BI)
			  (BI M		(BI OI MI D F))
			  (BI MI	BI)
			  (BI S		(BI OI MI D F))
			  (BI SI	BI)
			  (BI F		BI)
			  (BI FI	BI)
			  
			  (D  EQ	D)
			  (D  B		B)
			  (D  BI	BI)
			  (D  D		D)
			  (D  DI	(EQ B BI D DI O OI M MI S SI F FI))
			  (D  O		(B O M D S))
			  (D  OI	(BI OI MI D F))
			  (D  M		B)
			  (D  MI	BI)
			  (D  S		D)
			  (D  SI	(BI OI MI D F))
			  (D  F		D)
			  (D  FI	(B O M D S))
			  
			  (DI EQ	DI)
			  (DI B		(B O M DI FI))
			  (DI BI	(BI OI DI MI SI))
			  (DI D		(O OI D DI EQ S SI F FI))
			  (DI DI	DI)
			  (DI O		(O DI FI))
			  (DI OI	(OI DI SI))
			  (DI M		(O DI FI))
			  (DI MI	(OI DI SI))
			  (DI S		(O DI FI))
			  (DI SI	DI)
			  (DI F		(OI DI SI))
			  (DI FI	DI)
			  
			  (O  EQ	O)
			  (O  B		B)
			  (O  BI	(BI OI DI MI SI))
			  (O  D		(O D S))
			  (O  DI	(B O M DI FI))
			  (O  O		(B O M))
			  (O  OI	(O OI D DI EQ S SI F FI))
			  (O  M		B)
			  (O  MI	(OI DI SI))
			  (O  S		O)
			  (O  SI	(O DI FI))
			  (O  F		(O D S))
			  (O  FI	(B O M))
			  
			  (OI EQ	OI)
			  (OI B		(B O M DI FI))
			  (OI BI	BI)
			  (OI D		(OI D F))
			  (OI DI	(BI OI DI MI SI))
			  (OI O		(O OI D DI EQ S SI F FI))
			  (OI OI	(BI OI MI))
			  (OI M		(O DI FI))
			  (OI MI	BI)
			  (OI S		(OI D F))
			  (OI SI	(BI OI MI))
			  (OI F		OI)
			  (OI FI	(OI DI SI))
			  
			  (M  EQ	M)
			  (M  B		B)
			  (M  BI	(BI OI DI MI SI))
			  (M  D		(O D S))
			  (M  DI	B)
			  (M  O		B)
			  (M  OI	(O D S))
			  (M  M		B)
			  (M  MI	(F FI EQ))
			  (M  S		M)
			  (M  SI	M)
			  (M  F		(O D S))
			  (M  FI	B)
			  
			  (MI EQ	MI)
			  (MI B		(B O M DI FI))
			  (MI BI	BI)
			  (MI D		(OI D F))
			  (MI DI	BI)
			  (MI O		(OI D F))
			  (MI OI	BI)
			  (MI M		(S SI EQ))
			  (MI MI	BI)
			  (MI S		(OI D F))
			  (MI SI	BI)
			  (MI F		MI)
			  (MI FI	MI)
	
			  (S  EQ	S)
			  (S  B		B)
			  (S  BI	BI)
			  (S  D		D)
			  (S  DI	(B O M DI FI))
			  (S  O		(B O M))
			  (S  OI	(OI D F))
			  (S  M		B)
			  (S  MI	MI)
			  (S  S		S)
			  (S  SI	(S SI EQ))
			  (S  F		D)
			  (S  FI	(B O M))
			  
			  (SI EQ	SI)
			  (SI B		(B O M DI FI))
			  (SI BI	BI)
			  (SI D		(OI D F))
			  (SI DI	DI)
			  (SI O		(O DI FI))
			  (SI OI	OI)
			  (SI M		(O DI FI))
			  (SI MI	MI)
			  (SI S		(S SI EQ))
			  (SI SI	SI)
			  (SI F		OI)
			  (SI FI	DI)
			  
			  
			  (F  EQ	F)
			  (F  B		B)
			  (F  BI	BI)
			  (F  D		D)
			  (F  DI	(BI OI DI MI SI))
			  (F  O		(O D S))
			  (F  OI	(BI OI MI))
			  (F  M		M)
			  (F  MI	BI)
			  (F  S		D)
			  (F  SI	(BI OI MI))
			  (F  F		F)
			  (F  FI	(F FI EQ))
			  	
			  (FI EQ	FI)
			  (FI B		B)
			  (FI BI	(BI OI DI MI SI))
			  (FI D		(O D S))
			  (FI DI	DI)
			  (FI O		O)
			  (FI OI	(OI SI DI))
			  (FI M		M)
			  (FI MI	(OI SI DI))
			  (FI S		O)
			  (FI SI	DI)
			  (FI F		(F FI EQ))
			  (FI FI	FI)
			  )
  :algebraic-specification ((*  ((1 ((a1 1))) < (1 ((a2 1))))  ; for all relations: A,B are proper non-empty intervals
				((1 ((b1 1))) < (1 ((b2 1)))))
			    (EQ ((1 ((a1 1))) = (1 ((b1 1))))
				((1 ((a2 1))) = (1 ((b2 1))))) ; equality
			    (b ((1 ((a2 1))) < (1 ((b1 1)))))  ; A before B
			    (bi ((1 ((b2 1))) < (1 ((a1 1))))) ; B before A
			    (d ((1 ((a1 1))) > (1 ((b1 1))))   ; A during B
			       ((1 ((a2 1))) < (1 ((b2 1)))))
			    (di ((1 ((a1 1))) < (1 ((b1 1))))  ; B during A
				((1 ((a2 1))) > (1 ((b2 1)))))
			    (o ((1 ((a1 1))) < (1 ((b1 1))))   ; A overlaps B
			       ((1 ((a2 1))) > (1 ((b1 1))))
			       ((1 ((a2 1))) < (1 ((b2 1)))))
			    (oi ((1 ((b1 1))) < (1 ((a1 1))))  ; B overlaps A
				((1 ((b2 1))) > (1 ((a1 1))))
				((1 ((b2 1))) < (1 ((a2 1)))))
			    (m ((1 ((a2 1))) = (1 ((b1 1)))))  ; A meets B
			    (mi ((1 ((b2 1))) = (1 ((a1 1))))) ; B meets A			    
			    (s ((1 ((a1 1))) = (1 ((b1 1))))   ; A starts B
			       ((1 ((a2 1))) < (1 ((b2 1)))))
			    (si ((1 ((b1 1))) = (1 ((a1 1))))  ; B starts A
				((1 ((b2 1))) < (1 ((a2 1)))))
			    (f ((1 ((a1 1))) > (1 ((b1 1))))   ; A finishes B
			       ((1 ((a2 1))) = (1 ((b2 1)))))
			    (fi ((1 ((b1 1))) > (1 ((a1 1))))  ; B finishes A
				((1 ((b2 1))) = (1 ((a2 1))))))
  :tractable-subsets (
		      ;; ORD-Horn
		      ( (EQ) (B) (BI) (D) (EQ D) (DI) (EQ DI) (O) (EQ O) (B O) (EQ B O) (D O) (EQ D O) (B D O) (EQ B D O) (DI O) (EQ DI O) (B DI O) (EQ B DI O) (OI) (EQ OI) (BI OI)
 (EQ BI OI) (D OI) (EQ D OI) (BI D OI) (EQ BI D OI) (DI OI) (EQ DI OI) (BI DI OI) (EQ BI DI OI) (D DI O OI) (EQ D DI O OI) (B D DI O OI) (EQ B D DI O OI)
 (BI D DI O OI) (EQ BI D DI O OI) (B BI D DI O OI) (EQ B BI D DI O OI) (M) (B M) (O M) (EQ O M) (B O M) (EQ B O M) (D O M) (EQ D O M) (B D O M) (EQ B D O M) (DI O M)
 (EQ DI O M) (B DI O M) (EQ B DI O M) (D DI O OI M) (EQ D DI O OI M) (B D DI O OI M) (EQ B D DI O OI M) (BI D DI O OI M) (EQ BI D DI O OI M) (B BI D DI O OI M)
 (EQ B BI D DI O OI M) (MI) (BI MI) (OI MI) (EQ OI MI) (BI OI MI) (EQ BI OI MI) (D OI MI) (EQ D OI MI) (BI D OI MI) (EQ BI D OI MI) (DI OI MI) (EQ DI OI MI)
 (BI DI OI MI) (EQ BI DI OI MI) (D DI O OI MI) (EQ D DI O OI MI) (B D DI O OI MI) (EQ B D DI O OI MI) (BI D DI O OI MI) (EQ BI D DI O OI MI) (B BI D DI O OI MI)
 (EQ B BI D DI O OI MI) (D DI O OI M MI) (EQ D DI O OI M MI) (B D DI O OI M MI) (EQ B D DI O OI M MI) (BI D DI O OI M MI) (EQ BI D DI O OI M MI) (B BI D DI O OI M MI)
 (EQ B BI D DI O OI M MI) (S) (EQ S) (D S) (EQ D S) (O S) (EQ O S) (B O S) (EQ B O S) (D O S) (EQ D O S) (B D O S) (EQ B D O S) (DI O S) (EQ DI O S) (B DI O S)
 (EQ B DI O S) (D OI S) (EQ D OI S) (BI D OI S) (EQ BI D OI S) (D DI O OI S) (EQ D DI O OI S) (B D DI O OI S) (EQ B D DI O OI S) (BI D DI O OI S) (EQ BI D DI O OI S)
 (B BI D DI O OI S) (EQ B BI D DI O OI S) (O M S) (EQ O M S) (B O M S) (EQ B O M S) (D O M S) (EQ D O M S) (B D O M S) (EQ B D O M S) (DI O M S) (EQ DI O M S)
 (B DI O M S) (EQ B DI O M S) (D DI O OI M S) (EQ D DI O OI M S) (B D DI O OI M S) (EQ B D DI O OI M S) (BI D DI O OI M S) (EQ BI D DI O OI M S) (B BI D DI O OI M S)
 (EQ B BI D DI O OI M S) (D OI MI S) (EQ D OI MI S) (BI D OI MI S) (EQ BI D OI MI S) (D DI O OI MI S) (EQ D DI O OI MI S) (B D DI O OI MI S) (EQ B D DI O OI MI S)
 (BI D DI O OI MI S) (EQ BI D DI O OI MI S) (B BI D DI O OI MI S) (EQ B BI D DI O OI MI S) (D DI O OI M MI S) (EQ D DI O OI M MI S) (B D DI O OI M MI S)
 (EQ B D DI O OI M MI S) (BI D DI O OI M MI S) (EQ BI D DI O OI M MI S) (B BI D DI O OI M MI S) (EQ B BI D DI O OI M MI S) (SI) (EQ SI) (DI SI) (EQ DI SI) (DI O SI)
 (EQ DI O SI) (B DI O SI) (EQ B DI O SI) (OI SI) (EQ OI SI) (BI OI SI) (EQ BI OI SI) (D OI SI) (EQ D OI SI) (BI D OI SI) (EQ BI D OI SI) (DI OI SI) (EQ DI OI SI)
 (BI DI OI SI) (EQ BI DI OI SI) (D DI O OI SI) (EQ D DI O OI SI) (B D DI O OI SI) (EQ B D DI O OI SI) (BI D DI O OI SI) (EQ BI D DI O OI SI) (B BI D DI O OI SI)
 (EQ B BI D DI O OI SI) (DI O M SI) (EQ DI O M SI) (B DI O M SI) (EQ B DI O M SI) (D DI O OI M SI) (EQ D DI O OI M SI) (B D DI O OI M SI) (EQ B D DI O OI M SI)
 (BI D DI O OI M SI) (EQ BI D DI O OI M SI) (B BI D DI O OI M SI) (EQ B BI D DI O OI M SI) (OI MI SI) (EQ OI MI SI) (BI OI MI SI) (EQ BI OI MI SI) (D OI MI SI)
 (EQ D OI MI SI) (BI D OI MI SI) (EQ BI D OI MI SI) (DI OI MI SI) (EQ DI OI MI SI) (BI DI OI MI SI) (EQ BI DI OI MI SI) (D DI O OI MI SI) (EQ D DI O OI MI SI)
 (B D DI O OI MI SI) (EQ B D DI O OI MI SI) (BI D DI O OI MI SI) (EQ BI D DI O OI MI SI) (B BI D DI O OI MI SI) (EQ B BI D DI O OI MI SI) (D DI O OI M MI SI)
 (EQ D DI O OI M MI SI) (B D DI O OI M MI SI) (EQ B D DI O OI M MI SI) (BI D DI O OI M MI SI) (EQ BI D DI O OI M MI SI) (B BI D DI O OI M MI SI)
 (EQ B BI D DI O OI M MI SI) (S SI) (EQ S SI) (DI O S SI) (EQ DI O S SI) (B DI O S SI) (EQ B DI O S SI) (D OI S SI) (EQ D OI S SI) (BI D OI S SI) (EQ BI D OI S SI)
 (D DI O OI S SI) (EQ D DI O OI S SI) (B D DI O OI S SI) (EQ B D DI O OI S SI) (BI D DI O OI S SI) (EQ BI D DI O OI S SI) (B BI D DI O OI S SI)
 (EQ B BI D DI O OI S SI) (DI O M S SI) (EQ DI O M S SI) (B DI O M S SI) (EQ B DI O M S SI) (D DI O OI M S SI) (EQ D DI O OI M S SI) (B D DI O OI M S SI)
 (EQ B D DI O OI M S SI) (BI D DI O OI M S SI) (EQ BI D DI O OI M S SI) (B BI D DI O OI M S SI) (EQ B BI D DI O OI M S SI) (D OI MI S SI) (EQ D OI MI S SI)
 (BI D OI MI S SI) (EQ BI D OI MI S SI) (D DI O OI MI S SI) (EQ D DI O OI MI S SI) (B D DI O OI MI S SI) (EQ B D DI O OI MI S SI) (BI D DI O OI MI S SI)
 (EQ BI D DI O OI MI S SI) (B BI D DI O OI MI S SI) (EQ B BI D DI O OI MI S SI) (D DI O OI M MI S SI) (EQ D DI O OI M MI S SI) (B D DI O OI M MI S SI)
 (EQ B D DI O OI M MI S SI) (BI D DI O OI M MI S SI) (EQ BI D DI O OI M MI S SI) (B BI D DI O OI M MI S SI) (EQ B BI D DI O OI M MI S SI) (F) (EQ F) (D F) (EQ D F)
 (D O F) (EQ D O F) (B D O F) (EQ B D O F) (OI F) (EQ OI F) (BI OI F) (EQ BI OI F) (D OI F) (EQ D OI F) (BI D OI F) (EQ BI D OI F) (DI OI F) (EQ DI OI F) (BI DI OI F)
 (EQ BI DI OI F) (D DI O OI F) (EQ D DI O OI F) (B D DI O OI F) (EQ B D DI O OI F) (BI D DI O OI F) (EQ BI D DI O OI F) (B BI D DI O OI F) (EQ B BI D DI O OI F)
 (D O M F) (EQ D O M F) (B D O M F) (EQ B D O M F) (D DI O OI M F) (EQ D DI O OI M F) (B D DI O OI M F) (EQ B D DI O OI M F) (BI D DI O OI M F) (EQ BI D DI O OI M F)
 (B BI D DI O OI M F) (EQ B BI D DI O OI M F) (OI MI F) (EQ OI MI F) (BI OI MI F) (EQ BI OI MI F) (D OI MI F) (EQ D OI MI F) (BI D OI MI F) (EQ BI D OI MI F)
 (DI OI MI F) (EQ DI OI MI F) (BI DI OI MI F) (EQ BI DI OI MI F) (D DI O OI MI F) (EQ D DI O OI MI F) (B D DI O OI MI F) (EQ B D DI O OI MI F) (BI D DI O OI MI F)
 (EQ BI D DI O OI MI F) (B BI D DI O OI MI F) (EQ B BI D DI O OI MI F) (D DI O OI M MI F) (EQ D DI O OI M MI F) (B D DI O OI M MI F) (EQ B D DI O OI M MI F)
 (BI D DI O OI M MI F) (EQ BI D DI O OI M MI F) (B BI D DI O OI M MI F) (EQ B BI D DI O OI M MI F) (D S F) (EQ D S F) (D O S F) (EQ D O S F) (B D O S F)
 (EQ B D O S F) (D OI S F) (EQ D OI S F) (BI D OI S F) (EQ BI D OI S F) (D DI O OI S F) (EQ D DI O OI S F) (B D DI O OI S F) (EQ B D DI O OI S F) (BI D DI O OI S F)
 (EQ BI D DI O OI S F) (B BI D DI O OI S F) (EQ B BI D DI O OI S F) (D O M S F) (EQ D O M S F) (B D O M S F) (EQ B D O M S F) (D DI O OI M S F) (EQ D DI O OI M S F)
 (B D DI O OI M S F) (EQ B D DI O OI M S F) (BI D DI O OI M S F) (EQ BI D DI O OI M S F) (B BI D DI O OI M S F) (EQ B BI D DI O OI M S F) (D OI MI S F)
 (EQ D OI MI S F) (BI D OI MI S F) (EQ BI D OI MI S F) (D DI O OI MI S F) (EQ D DI O OI MI S F) (B D DI O OI MI S F) (EQ B D DI O OI MI S F) (BI D DI O OI MI S F)
 (EQ BI D DI O OI MI S F) (B BI D DI O OI MI S F) (EQ B BI D DI O OI MI S F) (D DI O OI M MI S F) (EQ D DI O OI M MI S F) (B D DI O OI M MI S F)
 (EQ B D DI O OI M MI S F) (BI D DI O OI M MI S F) (EQ BI D DI O OI M MI S F) (B BI D DI O OI M MI S F) (EQ B BI D DI O OI M MI S F) (OI SI F) (EQ OI SI F)
 (BI OI SI F) (EQ BI OI SI F) (D OI SI F) (EQ D OI SI F) (BI D OI SI F) (EQ BI D OI SI F) (DI OI SI F) (EQ DI OI SI F) (BI DI OI SI F) (EQ BI DI OI SI F)
 (D DI O OI SI F) (EQ D DI O OI SI F) (B D DI O OI SI F) (EQ B D DI O OI SI F) (BI D DI O OI SI F) (EQ BI D DI O OI SI F) (B BI D DI O OI SI F)
 (EQ B BI D DI O OI SI F) (D DI O OI M SI F) (EQ D DI O OI M SI F) (B D DI O OI M SI F) (EQ B D DI O OI M SI F) (BI D DI O OI M SI F) (EQ BI D DI O OI M SI F)
 (B BI D DI O OI M SI F) (EQ B BI D DI O OI M SI F) (OI MI SI F) (EQ OI MI SI F) (BI OI MI SI F) (EQ BI OI MI SI F) (D OI MI SI F) (EQ D OI MI SI F) (BI D OI MI SI F)
 (EQ BI D OI MI SI F) (DI OI MI SI F) (EQ DI OI MI SI F) (BI DI OI MI SI F) (EQ BI DI OI MI SI F) (D DI O OI MI SI F) (EQ D DI O OI MI SI F) (B D DI O OI MI SI F)
 (EQ B D DI O OI MI SI F) (BI D DI O OI MI SI F) (EQ BI D DI O OI MI SI F) (B BI D DI O OI MI SI F) (EQ B BI D DI O OI MI SI F) (D DI O OI M MI SI F)
 (EQ D DI O OI M MI SI F) (B D DI O OI M MI SI F) (EQ B D DI O OI M MI SI F) (BI D DI O OI M MI SI F) (EQ BI D DI O OI M MI SI F) (B BI D DI O OI M MI SI F)
 (EQ B BI D DI O OI M MI SI F) (D OI S SI F) (EQ D OI S SI F) (BI D OI S SI F) (EQ BI D OI S SI F) (D DI O OI S SI F) (EQ D DI O OI S SI F) (B D DI O OI S SI F)
 (EQ B D DI O OI S SI F) (BI D DI O OI S SI F) (EQ BI D DI O OI S SI F) (B BI D DI O OI S SI F) (EQ B BI D DI O OI S SI F) (D DI O OI M S SI F)
 (EQ D DI O OI M S SI F) (B D DI O OI M S SI F) (EQ B D DI O OI M S SI F) (BI D DI O OI M S SI F) (EQ BI D DI O OI M S SI F) (B BI D DI O OI M S SI F)
 (EQ B BI D DI O OI M S SI F) (D OI MI S SI F) (EQ D OI MI S SI F) (BI D OI MI S SI F) (EQ BI D OI MI S SI F) (D DI O OI MI S SI F) (EQ D DI O OI MI S SI F)
 (B D DI O OI MI S SI F) (EQ B D DI O OI MI S SI F) (BI D DI O OI MI S SI F) (EQ BI D DI O OI MI S SI F) (B BI D DI O OI MI S SI F) (EQ B BI D DI O OI MI S SI F)
 (D DI O OI M MI S SI F) (EQ D DI O OI M MI S SI F) (B D DI O OI M MI S SI F) (EQ B D DI O OI M MI S SI F) (BI D DI O OI M MI S SI F) (EQ BI D DI O OI M MI S SI F)
 (B BI D DI O OI M MI S SI F) (EQ B BI D DI O OI M MI S SI F) (FI) (EQ FI) (DI FI) (EQ DI FI) (O FI) (EQ O FI) (B O FI) (EQ B O FI) (D O FI) (EQ D O FI) (B D O FI)
 (EQ B D O FI) (DI O FI) (EQ DI O FI) (B DI O FI) (EQ B DI O FI) (DI OI FI) (EQ DI OI FI) (BI DI OI FI) (EQ BI DI OI FI) (D DI O OI FI) (EQ D DI O OI FI)
 (B D DI O OI FI) (EQ B D DI O OI FI) (BI D DI O OI FI) (EQ BI D DI O OI FI) (B BI D DI O OI FI) (EQ B BI D DI O OI FI) (O M FI) (EQ O M FI) (B O M FI) (EQ B O M FI)
 (D O M FI) (EQ D O M FI) (B D O M FI) (EQ B D O M FI) (DI O M FI) (EQ DI O M FI) (B DI O M FI) (EQ B DI O M FI) (D DI O OI M FI) (EQ D DI O OI M FI)
 (B D DI O OI M FI) (EQ B D DI O OI M FI) (BI D DI O OI M FI) (EQ BI D DI O OI M FI) (B BI D DI O OI M FI) (EQ B BI D DI O OI M FI) (DI OI MI FI) (EQ DI OI MI FI)
 (BI DI OI MI FI) (EQ BI DI OI MI FI) (D DI O OI MI FI) (EQ D DI O OI MI FI) (B D DI O OI MI FI) (EQ B D DI O OI MI FI) (BI D DI O OI MI FI) (EQ BI D DI O OI MI FI)
 (B BI D DI O OI MI FI) (EQ B BI D DI O OI MI FI) (D DI O OI M MI FI) (EQ D DI O OI M MI FI) (B D DI O OI M MI FI) (EQ B D DI O OI M MI FI) (BI D DI O OI M MI FI)
 (EQ BI D DI O OI M MI FI) (B BI D DI O OI M MI FI) (EQ B BI D DI O OI M MI FI) (O S FI) (EQ O S FI) (B O S FI) (EQ B O S FI) (D O S FI) (EQ D O S FI) (B D O S FI)
 (EQ B D O S FI) (DI O S FI) (EQ DI O S FI) (B DI O S FI) (EQ B DI O S FI) (D DI O OI S FI) (EQ D DI O OI S FI) (B D DI O OI S FI) (EQ B D DI O OI S FI)
 (BI D DI O OI S FI) (EQ BI D DI O OI S FI) (B BI D DI O OI S FI) (EQ B BI D DI O OI S FI) (O M S FI) (EQ O M S FI) (B O M S FI) (EQ B O M S FI) (D O M S FI)
 (EQ D O M S FI) (B D O M S FI) (EQ B D O M S FI) (DI O M S FI) (EQ DI O M S FI) (B DI O M S FI) (EQ B DI O M S FI) (D DI O OI M S FI) (EQ D DI O OI M S FI)
 (B D DI O OI M S FI) (EQ B D DI O OI M S FI) (BI D DI O OI M S FI) (EQ BI D DI O OI M S FI) (B BI D DI O OI M S FI) (EQ B BI D DI O OI M S FI) (D DI O OI MI S FI)
 (EQ D DI O OI MI S FI) (B D DI O OI MI S FI) (EQ B D DI O OI MI S FI) (BI D DI O OI MI S FI) (EQ BI D DI O OI MI S FI) (B BI D DI O OI MI S FI)
 (EQ B BI D DI O OI MI S FI) (D DI O OI M MI S FI) (EQ D DI O OI M MI S FI) (B D DI O OI M MI S FI) (EQ B D DI O OI M MI S FI) (BI D DI O OI M MI S FI)
 (EQ BI D DI O OI M MI S FI) (B BI D DI O OI M MI S FI) (EQ B BI D DI O OI M MI S FI) (DI SI FI) (EQ DI SI FI) (DI O SI FI) (EQ DI O SI FI) (B DI O SI FI)
 (EQ B DI O SI FI) (DI OI SI FI) (EQ DI OI SI FI) (BI DI OI SI FI) (EQ BI DI OI SI FI) (D DI O OI SI FI) (EQ D DI O OI SI FI) (B D DI O OI SI FI)
 (EQ B D DI O OI SI FI) (BI D DI O OI SI FI) (EQ BI D DI O OI SI FI) (B BI D DI O OI SI FI) (EQ B BI D DI O OI SI FI) (DI O M SI FI) (EQ DI O M SI FI)
 (B DI O M SI FI) (EQ B DI O M SI FI) (D DI O OI M SI FI) (EQ D DI O OI M SI FI) (B D DI O OI M SI FI) (EQ B D DI O OI M SI FI) (BI D DI O OI M SI FI)
 (EQ BI D DI O OI M SI FI) (B BI D DI O OI M SI FI) (EQ B BI D DI O OI M SI FI) (DI OI MI SI FI) (EQ DI OI MI SI FI) (BI DI OI MI SI FI) (EQ BI DI OI MI SI FI)
 (D DI O OI MI SI FI) (EQ D DI O OI MI SI FI) (B D DI O OI MI SI FI) (EQ B D DI O OI MI SI FI) (BI D DI O OI MI SI FI) (EQ BI D DI O OI MI SI FI)
 (B BI D DI O OI MI SI FI) (EQ B BI D DI O OI MI SI FI) (D DI O OI M MI SI FI) (EQ D DI O OI M MI SI FI) (B D DI O OI M MI SI FI) (EQ B D DI O OI M MI SI FI)
 (BI D DI O OI M MI SI FI) (EQ BI D DI O OI M MI SI FI) (B BI D DI O OI M MI SI FI) (EQ B BI D DI O OI M MI SI FI) (DI O S SI FI) (EQ DI O S SI FI) (B DI O S SI FI)
 (EQ B DI O S SI FI) (D DI O OI S SI FI) (EQ D DI O OI S SI FI) (B D DI O OI S SI FI) (EQ B D DI O OI S SI FI) (BI D DI O OI S SI FI) (EQ BI D DI O OI S SI FI)
 (B BI D DI O OI S SI FI) (EQ B BI D DI O OI S SI FI) (DI O M S SI FI) (EQ DI O M S SI FI) (B DI O M S SI FI) (EQ B DI O M S SI FI) (D DI O OI M S SI FI)
 (EQ D DI O OI M S SI FI) (B D DI O OI M S SI FI) (EQ B D DI O OI M S SI FI) (BI D DI O OI M S SI FI) (EQ BI D DI O OI M S SI FI) (B BI D DI O OI M S SI FI)
 (EQ B BI D DI O OI M S SI FI) (D DI O OI MI S SI FI) (EQ D DI O OI MI S SI FI) (B D DI O OI MI S SI FI) (EQ B D DI O OI MI S SI FI) (BI D DI O OI MI S SI FI)
 (EQ BI D DI O OI MI S SI FI) (B BI D DI O OI MI S SI FI) (EQ B BI D DI O OI MI S SI FI) (D DI O OI M MI S SI FI) (EQ D DI O OI M MI S SI FI)
 (B D DI O OI M MI S SI FI) (EQ B D DI O OI M MI S SI FI) (BI D DI O OI M MI S SI FI) (EQ BI D DI O OI M MI S SI FI) (B BI D DI O OI M MI S SI FI)
 (EQ B BI D DI O OI M MI S SI FI) (F FI) (EQ F FI) (D O F FI) (EQ D O F FI) (B D O F FI) (EQ B D O F FI) (DI OI F FI) (EQ DI OI F FI) (BI DI OI F FI)
 (EQ BI DI OI F FI) (D DI O OI F FI) (EQ D DI O OI F FI) (B D DI O OI F FI) (EQ B D DI O OI F FI) (BI D DI O OI F FI) (EQ BI D DI O OI F FI) (B BI D DI O OI F FI)
 (EQ B BI D DI O OI F FI) (D O M F FI) (EQ D O M F FI) (B D O M F FI) (EQ B D O M F FI) (D DI O OI M F FI) (EQ D DI O OI M F FI) (B D DI O OI M F FI)
 (EQ B D DI O OI M F FI) (BI D DI O OI M F FI) (EQ BI D DI O OI M F FI) (B BI D DI O OI M F FI) (EQ B BI D DI O OI M F FI) (DI OI MI F FI) (EQ DI OI MI F FI)
 (BI DI OI MI F FI) (EQ BI DI OI MI F FI) (D DI O OI MI F FI) (EQ D DI O OI MI F FI) (B D DI O OI MI F FI) (EQ B D DI O OI MI F FI) (BI D DI O OI MI F FI)
 (EQ BI D DI O OI MI F FI) (B BI D DI O OI MI F FI) (EQ B BI D DI O OI MI F FI) (D DI O OI M MI F FI) (EQ D DI O OI M MI F FI) (B D DI O OI M MI F FI)
 (EQ B D DI O OI M MI F FI) (BI D DI O OI M MI F FI) (EQ BI D DI O OI M MI F FI) (B BI D DI O OI M MI F FI) (EQ B BI D DI O OI M MI F FI) (D O S F FI) (EQ D O S F FI)
 (B D O S F FI) (EQ B D O S F FI) (D DI O OI S F FI) (EQ D DI O OI S F FI) (B D DI O OI S F FI) (EQ B D DI O OI S F FI) (BI D DI O OI S F FI) (EQ BI D DI O OI S F FI)
 (B BI D DI O OI S F FI) (EQ B BI D DI O OI S F FI) (D O M S F FI) (EQ D O M S F FI) (B D O M S F FI) (EQ B D O M S F FI) (D DI O OI M S F FI) (EQ D DI O OI M S F FI)
 (B D DI O OI M S F FI) (EQ B D DI O OI M S F FI) (BI D DI O OI M S F FI) (EQ BI D DI O OI M S F FI) (B BI D DI O OI M S F FI) (EQ B BI D DI O OI M S F FI)
 (D DI O OI MI S F FI) (EQ D DI O OI MI S F FI) (B D DI O OI MI S F FI) (EQ B D DI O OI MI S F FI) (BI D DI O OI MI S F FI) (EQ BI D DI O OI MI S F FI)
 (B BI D DI O OI MI S F FI) (EQ B BI D DI O OI MI S F FI) (D DI O OI M MI S F FI) (EQ D DI O OI M MI S F FI) (B D DI O OI M MI S F FI) (EQ B D DI O OI M MI S F FI)
 (BI D DI O OI M MI S F FI) (EQ BI D DI O OI M MI S F FI) (B BI D DI O OI M MI S F FI) (EQ B BI D DI O OI M MI S F FI) (DI OI SI F FI) (EQ DI OI SI F FI)
 (BI DI OI SI F FI) (EQ BI DI OI SI F FI) (D DI O OI SI F FI) (EQ D DI O OI SI F FI) (B D DI O OI SI F FI) (EQ B D DI O OI SI F FI) (BI D DI O OI SI F FI)
 (EQ BI D DI O OI SI F FI) (B BI D DI O OI SI F FI) (EQ B BI D DI O OI SI F FI) (D DI O OI M SI F FI) (EQ D DI O OI M SI F FI) (B D DI O OI M SI F FI)
 (EQ B D DI O OI M SI F FI) (BI D DI O OI M SI F FI) (EQ BI D DI O OI M SI F FI) (B BI D DI O OI M SI F FI) (EQ B BI D DI O OI M SI F FI) (DI OI MI SI F FI)
 (EQ DI OI MI SI F FI) (BI DI OI MI SI F FI) (EQ BI DI OI MI SI F FI) (D DI O OI MI SI F FI) (EQ D DI O OI MI SI F FI) (B D DI O OI MI SI F FI)
 (EQ B D DI O OI MI SI F FI) (BI D DI O OI MI SI F FI) (EQ BI D DI O OI MI SI F FI) (B BI D DI O OI MI SI F FI) (EQ B BI D DI O OI MI SI F FI)
 (D DI O OI M MI SI F FI) (EQ D DI O OI M MI SI F FI) (B D DI O OI M MI SI F FI) (EQ B D DI O OI M MI SI F FI) (BI D DI O OI M MI SI F FI)
 (EQ BI D DI O OI M MI SI F FI) (B BI D DI O OI M MI SI F FI) (EQ B BI D DI O OI M MI SI F FI) (D DI O OI S SI F FI) (EQ D DI O OI S SI F FI) (B D DI O OI S SI F FI)
 (EQ B D DI O OI S SI F FI) (BI D DI O OI S SI F FI) (EQ BI D DI O OI S SI F FI) (B BI D DI O OI S SI F FI) (EQ B BI D DI O OI S SI F FI) (D DI O OI M S SI F FI)
 (EQ D DI O OI M S SI F FI) (B D DI O OI M S SI F FI) (EQ B D DI O OI M S SI F FI) (BI D DI O OI M S SI F FI) (EQ BI D DI O OI M S SI F FI)
 (B BI D DI O OI M S SI F FI) (EQ B BI D DI O OI M S SI F FI) (D DI O OI MI S SI F FI) (EQ D DI O OI MI S SI F FI) (B D DI O OI MI S SI F FI)
 (EQ B D DI O OI MI S SI F FI) (BI D DI O OI MI S SI F FI) (EQ BI D DI O OI MI S SI F FI) (B BI D DI O OI MI S SI F FI) (EQ B BI D DI O OI MI S SI F FI)
 (D DI O OI M MI S SI F FI) (EQ D DI O OI M MI S SI F FI) (B D DI O OI M MI S SI F FI) (EQ B D DI O OI M MI S SI F FI) (BI D DI O OI M MI S SI F FI)
 (EQ BI D DI O OI M MI S SI F FI) (B BI D DI O OI M MI S SI F FI) (EQ B BI D DI O OI M MI S SI F FI))
 )

)


