(def-calculus "Dipole relation algebra fine projected (DRA_op)"
	:arity			:binary 
	:basis-entity		:2d-oriented-point
	:parametric?		nil
	:identity-relation	SAMEfront
	:converse-operation (
( BACKback BACKback )
( BACKfront FRONTback )
( BACKleft LEFTback )
( BACKright RIGHTback )
( FRONTback BACKfront )
( FRONTfront FRONTfront )
( FRONTleft LEFTfront )
( FRONTright RIGHTfront )
( LEFTback BACKleft )
( LEFTfront FRONTleft )
( LEFTleft+ LEFTleft- )
( LEFTleft- LEFTleft+ )
( LEFTleftA LEFTleftA )
( LEFTright+ RIGHTleft- )
( LEFTright- RIGHTleft+ )
( LEFTrightP RIGHTleftP )
( RIGHTback BACKright )
( RIGHTfront FRONTright )
( RIGHTleft+ LEFTright- )
( RIGHTleft- LEFTright+ )
( RIGHTleftP LEFTrightP )
( RIGHTright+ RIGHTright- )
( RIGHTright- RIGHTright+ )
( RIGHTrightA RIGHTrightA )
( SAMEback SAMEback )
( SAMEfront SAMEfront )
( SAMEleft SAMEright )
( SAMEright SAMEleft )
	)
	:base-relations
		( BACKback BACKfront BACKleft BACKright FRONTback FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEfront SAMEleft SAMEright )
	:composition-operation
	(
( BACKback BACKback ( BACKfront FRONTback SAMEfront ))
( BACKback BACKfront ( BACKback FRONTfront SAMEback ))
( BACKback BACKleft ( BACKright FRONTleft SAMEleft ))
( BACKback BACKright ( BACKleft FRONTright SAMEright ))
( BACKback FRONTback ( BACKback ))
( BACKback FRONTfront ( BACKfront ))
( BACKback FRONTleft ( BACKleft ))
( BACKback FRONTright ( BACKright ))
( BACKback LEFTback ( RIGHTleft- ))
( BACKback LEFTfront ( RIGHTright+ ))
( BACKback LEFTleft+ ( RIGHTleft- ))
( BACKback LEFTleft- ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( BACKback LEFTleftA ( RIGHTleftP ))
( BACKback LEFTright+ ( RIGHTback RIGHTleft- RIGHTright- ))
( BACKback LEFTright- ( RIGHTright+ ))
( BACKback LEFTrightP ( RIGHTrightA ))
( BACKback RIGHTback ( LEFTright+ ))
( BACKback RIGHTfront ( LEFTleft- ))
( BACKback RIGHTleft+ ( LEFTleft- ))
( BACKback RIGHTleft- ( LEFTback LEFTleft+ LEFTright+ ))
( BACKback RIGHTleftP ( LEFTleftA ))
( BACKback RIGHTright+ ( LEFTfront LEFTleft- LEFTright- ))
( BACKback RIGHTright- ( LEFTright+ ))
( BACKback RIGHTrightA ( LEFTrightP ))
( BACKback SAMEback ( BACKfront ))
( BACKback SAMEfront ( BACKback ))
( BACKback SAMEleft ( BACKleft ))
( BACKback SAMEright ( BACKright ))
( BACKfront BACKback ( BACKback ))
( BACKfront BACKfront ( BACKfront ))
( BACKfront BACKleft ( BACKleft ))
( BACKfront BACKright ( BACKright ))
( BACKfront FRONTback ( BACKfront FRONTback SAMEfront ))
( BACKfront FRONTfront ( BACKback FRONTfront SAMEback ))
( BACKfront FRONTleft ( BACKright FRONTleft SAMEleft ))
( BACKfront FRONTright ( BACKleft FRONTright SAMEright ))
( BACKfront LEFTback ( LEFTright+ ))
( BACKfront LEFTfront ( LEFTleft- ))
( BACKfront LEFTleft+ ( LEFTback LEFTleft+ LEFTright+ ))
( BACKfront LEFTleft- ( LEFTleft- ))
( BACKfront LEFTleftA ( LEFTleftA ))
( BACKfront LEFTright+ ( LEFTright+ ))
( BACKfront LEFTright- ( LEFTfront LEFTleft- LEFTright- ))
( BACKfront LEFTrightP ( LEFTrightP ))
( BACKfront RIGHTback ( RIGHTleft- ))
( BACKfront RIGHTfront ( RIGHTright+ ))
( BACKfront RIGHTleft+ ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( BACKfront RIGHTleft- ( RIGHTleft- ))
( BACKfront RIGHTleftP ( RIGHTleftP ))
( BACKfront RIGHTright+ ( RIGHTright+ ))
( BACKfront RIGHTright- ( RIGHTback RIGHTleft- RIGHTright- ))
( BACKfront RIGHTrightA ( RIGHTrightA ))
( BACKfront SAMEback ( BACKback ))
( BACKfront SAMEfront ( BACKfront ))
( BACKfront SAMEleft ( BACKright ))
( BACKfront SAMEright ( BACKleft ))
( BACKleft BACKback ( LEFTright+ ))
( BACKleft BACKfront ( LEFTleft- ))
( BACKleft BACKleft ( LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ ))
( BACKleft BACKright ( LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP ))
( BACKleft FRONTback ( RIGHTleft- ))
( BACKleft FRONTfront ( RIGHTright+ ))
( BACKleft FRONTleft ( RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( BACKleft FRONTright ( RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( BACKleft LEFTback ( BACKfront FRONTback LEFTright+ RIGHTleft- SAMEfront ))
( BACKleft LEFTfront ( BACKback FRONTfront LEFTleft- RIGHTright+ SAMEback ))
( BACKleft LEFTleft+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ SAMEleft ))
( BACKleft LEFTleft- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( BACKleft LEFTleftA ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( BACKleft LEFTright+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( BACKleft LEFTright- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEright ))
( BACKleft LEFTrightP ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( BACKleft RIGHTback ( BACKback LEFTright+ RIGHTleft- ))
( BACKleft RIGHTfront ( BACKfront LEFTleft- RIGHTright+ ))
( BACKleft RIGHTleft+ ( BACKleft LEFTleft- RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( BACKleft RIGHTleft- ( BACKleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTleft- ))
( BACKleft RIGHTleftP ( BACKleft LEFTleft- RIGHTleft- ))
( BACKleft RIGHTright+ ( BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( BACKleft RIGHTright- ( BACKright LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( BACKleft RIGHTrightA ( BACKright LEFTright+ RIGHTright+ ))
( BACKleft SAMEback ( BACKright ))
( BACKleft SAMEfront ( BACKleft ))
( BACKleft SAMEleft ( BACKfront BACKleft BACKright ))
( BACKleft SAMEright ( BACKback BACKleft BACKright ))
( BACKright BACKback ( RIGHTleft- ))
( BACKright BACKfront ( RIGHTright+ ))
( BACKright BACKleft ( RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( BACKright BACKright ( RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( BACKright FRONTback ( LEFTright+ ))
( BACKright FRONTfront ( LEFTleft- ))
( BACKright FRONTleft ( LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ ))
( BACKright FRONTright ( LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP ))
( BACKright LEFTback ( BACKback LEFTright+ RIGHTleft- ))
( BACKright LEFTfront ( BACKfront LEFTleft- RIGHTright+ ))
( BACKright LEFTleft+ ( BACKleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTleft- ))
( BACKright LEFTleft- ( BACKleft LEFTleft- RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( BACKright LEFTleftA ( BACKleft LEFTleft- RIGHTleft- ))
( BACKright LEFTright+ ( BACKright LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( BACKright LEFTright- ( BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( BACKright LEFTrightP ( BACKright LEFTright+ RIGHTright+ ))
( BACKright RIGHTback ( BACKfront FRONTback LEFTright+ RIGHTleft- SAMEfront ))
( BACKright RIGHTfront ( BACKback FRONTfront LEFTleft- RIGHTright+ SAMEback ))
( BACKright RIGHTleft+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( BACKright RIGHTleft- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ SAMEleft ))
( BACKright RIGHTleftP ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( BACKright RIGHTright+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEright ))
( BACKright RIGHTright- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( BACKright RIGHTrightA ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( BACKright SAMEback ( BACKleft ))
( BACKright SAMEfront ( BACKright ))
( BACKright SAMEleft ( BACKback BACKleft BACKright ))
( BACKright SAMEright ( BACKfront BACKleft BACKright ))
( FRONTback BACKback ( BACKback FRONTfront SAMEback ))
( FRONTback BACKfront ( BACKfront FRONTback SAMEfront ))
( FRONTback BACKleft ( BACKleft FRONTright SAMEright ))
( FRONTback BACKright ( BACKright FRONTleft SAMEleft ))
( FRONTback FRONTback ( FRONTback ))
( FRONTback FRONTfront ( FRONTfront ))
( FRONTback FRONTleft ( FRONTleft ))
( FRONTback FRONTright ( FRONTright ))
( FRONTback LEFTback ( LEFTleft+ ))
( FRONTback LEFTfront ( LEFTright- ))
( FRONTback LEFTleft+ ( LEFTleft+ ))
( FRONTback LEFTleft- ( LEFTfront LEFTleft- LEFTright- ))
( FRONTback LEFTleftA ( LEFTleftA ))
( FRONTback LEFTright+ ( LEFTback LEFTleft+ LEFTright+ ))
( FRONTback LEFTright- ( LEFTright- ))
( FRONTback LEFTrightP ( LEFTrightP ))
( FRONTback RIGHTback ( RIGHTright- ))
( FRONTback RIGHTfront ( RIGHTleft+ ))
( FRONTback RIGHTleft+ ( RIGHTleft+ ))
( FRONTback RIGHTleft- ( RIGHTback RIGHTleft- RIGHTright- ))
( FRONTback RIGHTleftP ( RIGHTleftP ))
( FRONTback RIGHTright+ ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( FRONTback RIGHTright- ( RIGHTright- ))
( FRONTback RIGHTrightA ( RIGHTrightA ))
( FRONTback SAMEback ( FRONTfront ))
( FRONTback SAMEfront ( FRONTback ))
( FRONTback SAMEleft ( FRONTleft ))
( FRONTback SAMEright ( FRONTright ))
( FRONTfront BACKback ( FRONTback ))
( FRONTfront BACKfront ( FRONTfront ))
( FRONTfront BACKleft ( FRONTleft ))
( FRONTfront BACKright ( FRONTright ))
( FRONTfront FRONTback ( BACKback FRONTfront SAMEback ))
( FRONTfront FRONTfront ( BACKfront FRONTback SAMEfront ))
( FRONTfront FRONTleft ( BACKleft FRONTright SAMEright ))
( FRONTfront FRONTright ( BACKright FRONTleft SAMEleft ))
( FRONTfront LEFTback ( RIGHTright- ))
( FRONTfront LEFTfront ( RIGHTleft+ ))
( FRONTfront LEFTleft+ ( RIGHTback RIGHTleft- RIGHTright- ))
( FRONTfront LEFTleft- ( RIGHTleft+ ))
( FRONTfront LEFTleftA ( RIGHTleftP ))
( FRONTfront LEFTright+ ( RIGHTright- ))
( FRONTfront LEFTright- ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( FRONTfront LEFTrightP ( RIGHTrightA ))
( FRONTfront RIGHTback ( LEFTleft+ ))
( FRONTfront RIGHTfront ( LEFTright- ))
( FRONTfront RIGHTleft+ ( LEFTfront LEFTleft- LEFTright- ))
( FRONTfront RIGHTleft- ( LEFTleft+ ))
( FRONTfront RIGHTleftP ( LEFTleftA ))
( FRONTfront RIGHTright+ ( LEFTright- ))
( FRONTfront RIGHTright- ( LEFTback LEFTleft+ LEFTright+ ))
( FRONTfront RIGHTrightA ( LEFTrightP ))
( FRONTfront SAMEback ( FRONTback ))
( FRONTfront SAMEfront ( FRONTfront ))
( FRONTfront SAMEleft ( FRONTright ))
( FRONTfront SAMEright ( FRONTleft ))
( FRONTleft BACKback ( RIGHTright- ))
( FRONTleft BACKfront ( RIGHTleft+ ))
( FRONTleft BACKleft ( RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( FRONTleft BACKright ( RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( FRONTleft FRONTback ( LEFTleft+ ))
( FRONTleft FRONTfront ( LEFTright- ))
( FRONTleft FRONTleft ( LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- ))
( FRONTleft FRONTright ( LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP ))
( FRONTleft LEFTback ( BACKback FRONTfront LEFTleft+ RIGHTright- SAMEback ))
( FRONTleft LEFTfront ( BACKfront FRONTback LEFTright- RIGHTleft+ SAMEfront ))
( FRONTleft LEFTleft+ ( BACKleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( FRONTleft LEFTleft- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- SAMEright ))
( FRONTleft LEFTleftA ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( FRONTleft LEFTright+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA SAMEleft ))
( FRONTleft LEFTright- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( FRONTleft LEFTrightP ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( FRONTleft RIGHTback ( FRONTback LEFTleft+ RIGHTright- ))
( FRONTleft RIGHTfront ( FRONTfront LEFTright- RIGHTleft+ ))
( FRONTleft RIGHTleft+ ( FRONTleft LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTleft+ ))
( FRONTleft RIGHTleft- ( FRONTleft LEFTleft+ RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( FRONTleft RIGHTleftP ( FRONTleft LEFTleft+ RIGHTleft+ ))
( FRONTleft RIGHTright+ ( FRONTright LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( FRONTleft RIGHTright- ( FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( FRONTleft RIGHTrightA ( FRONTright LEFTright- RIGHTright- ))
( FRONTleft SAMEback ( FRONTright ))
( FRONTleft SAMEfront ( FRONTleft ))
( FRONTleft SAMEleft ( FRONTfront FRONTleft FRONTright ))
( FRONTleft SAMEright ( FRONTback FRONTleft FRONTright ))
( FRONTright BACKback ( LEFTleft+ ))
( FRONTright BACKfront ( LEFTright- ))
( FRONTright BACKleft ( LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- ))
( FRONTright BACKright ( LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP ))
( FRONTright FRONTback ( RIGHTright- ))
( FRONTright FRONTfront ( RIGHTleft+ ))
( FRONTright FRONTleft ( RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( FRONTright FRONTright ( RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( FRONTright LEFTback ( FRONTback LEFTleft+ RIGHTright- ))
( FRONTright LEFTfront ( FRONTfront LEFTright- RIGHTleft+ ))
( FRONTright LEFTleft+ ( FRONTleft LEFTleft+ RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( FRONTright LEFTleft- ( FRONTleft LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTleft+ ))
( FRONTright LEFTleftA ( FRONTleft LEFTleft+ RIGHTleft+ ))
( FRONTright LEFTright+ ( FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( FRONTright LEFTright- ( FRONTright LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( FRONTright LEFTrightP ( FRONTright LEFTright- RIGHTright- ))
( FRONTright RIGHTback ( BACKback FRONTfront LEFTleft+ RIGHTright- SAMEback ))
( FRONTright RIGHTfront ( BACKfront FRONTback LEFTright- RIGHTleft+ SAMEfront ))
( FRONTright RIGHTleft+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- SAMEright ))
( FRONTright RIGHTleft- ( BACKleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( FRONTright RIGHTleftP ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( FRONTright RIGHTright+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( FRONTright RIGHTright- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA SAMEleft ))
( FRONTright RIGHTrightA ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( FRONTright SAMEback ( FRONTleft ))
( FRONTright SAMEfront ( FRONTright ))
( FRONTright SAMEleft ( FRONTback FRONTleft FRONTright ))
( FRONTright SAMEright ( FRONTfront FRONTleft FRONTright ))
( LEFTback BACKback ( LEFTfront RIGHTback SAMEright ))
( LEFTback BACKfront ( LEFTback RIGHTfront SAMEleft ))
( LEFTback BACKleft ( LEFTright+ LEFTright- LEFTrightP RIGHTleft+ RIGHTleft- RIGHTleftP SAMEfront SAMEleft SAMEright ))
( LEFTback BACKright ( LEFTleft+ LEFTleft- LEFTleftA RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( LEFTback FRONTback ( LEFTback ))
( LEFTback FRONTfront ( LEFTfront ))
( LEFTback FRONTleft ( LEFTleft+ LEFTleft- LEFTleftA ))
( LEFTback FRONTright ( LEFTright+ LEFTright- LEFTrightP ))
( LEFTback LEFTback ( BACKleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft- ))
( LEFTback LEFTfront ( BACKright LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTback LEFTleft+ ( BACKleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft- ))
( LEFTback LEFTleft- ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( LEFTback LEFTleftA ( BACKleft LEFTleft- RIGHTleft- ))
( LEFTback LEFTright+ ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTback LEFTright- ( BACKright LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTback LEFTrightP ( BACKright LEFTright+ RIGHTright+ ))
( LEFTback RIGHTback ( FRONTright LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTback RIGHTfront ( FRONTleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft+ ))
( LEFTback RIGHTleft+ ( FRONTleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft+ ))
( LEFTback RIGHTleft- ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( LEFTback RIGHTleftP ( FRONTleft LEFTleft+ RIGHTleft+ ))
( LEFTback RIGHTright+ ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTback RIGHTright- ( FRONTright LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTback RIGHTrightA ( FRONTright LEFTright- RIGHTright- ))
( LEFTback SAMEback ( LEFTfront ))
( LEFTback SAMEfront ( LEFTback ))
( LEFTback SAMEleft ( LEFTleft+ LEFTleft- LEFTleftA ))
( LEFTback SAMEright ( LEFTright+ LEFTright- LEFTrightP ))
( LEFTfront BACKback ( LEFTback ))
( LEFTfront BACKfront ( LEFTfront ))
( LEFTfront BACKleft ( LEFTleft+ LEFTleft- LEFTleftA ))
( LEFTfront BACKright ( LEFTright+ LEFTright- LEFTrightP ))
( LEFTfront FRONTback ( LEFTfront RIGHTback SAMEright ))
( LEFTfront FRONTfront ( LEFTback RIGHTfront SAMEleft ))
( LEFTfront FRONTleft ( LEFTright+ LEFTright- LEFTrightP RIGHTleft+ RIGHTleft- RIGHTleftP SAMEfront SAMEleft SAMEright ))
( LEFTfront FRONTright ( LEFTleft+ LEFTleft- LEFTleftA RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( LEFTfront LEFTback ( FRONTright LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTfront LEFTfront ( FRONTleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft+ ))
( LEFTfront LEFTleft+ ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( LEFTfront LEFTleft- ( FRONTleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft+ ))
( LEFTfront LEFTleftA ( FRONTleft LEFTleft+ RIGHTleft+ ))
( LEFTfront LEFTright+ ( FRONTright LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTfront LEFTright- ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTfront LEFTrightP ( FRONTright LEFTright- RIGHTright- ))
( LEFTfront RIGHTback ( BACKleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft- ))
( LEFTfront RIGHTfront ( BACKright LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTfront RIGHTleft+ ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( LEFTfront RIGHTleft- ( BACKleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft- ))
( LEFTfront RIGHTleftP ( BACKleft LEFTleft- RIGHTleft- ))
( LEFTfront RIGHTright+ ( BACKright LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTfront RIGHTright- ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTfront RIGHTrightA ( BACKright LEFTright+ RIGHTright+ ))
( LEFTfront SAMEback ( LEFTback ))
( LEFTfront SAMEfront ( LEFTfront ))
( LEFTfront SAMEleft ( LEFTright+ LEFTright- LEFTrightP ))
( LEFTfront SAMEright ( LEFTleft+ LEFTleft- LEFTleftA ))
( LEFTleft+ BACKback ( FRONTright LEFTright- RIGHTright- ))
( LEFTleft+ BACKfront ( FRONTleft LEFTleft+ RIGHTleft+ ))
( LEFTleft+ BACKleft ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( LEFTleft+ BACKright ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTleft+ FRONTback ( LEFTleft+ ))
( LEFTleft+ FRONTfront ( LEFTright- ))
( LEFTleft+ FRONTleft ( LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- ))
( LEFTleft+ FRONTright ( LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP ))
( LEFTleft+ LEFTback ( BACKleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleft+ LEFTfront ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleft+ LEFTleft+ ( BACKleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleft+ LEFTleft- ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( LEFTleft+ LEFTleftA ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleft+ LEFTright+ ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( LEFTleft+ LEFTright- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleft+ LEFTrightP ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleft+ RIGHTback ( FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTleft+ RIGHTfront ( FRONTleft LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTleft+ ))
( LEFTleft+ RIGHTleft+ ( FRONTleft LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTleft+ ))
( LEFTleft+ RIGHTleft- ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( LEFTleft+ RIGHTleftP ( FRONTleft LEFTleft+ RIGHTleft+ ))
( LEFTleft+ RIGHTright+ ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTleft+ RIGHTright- ( FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTleft+ RIGHTrightA ( FRONTright LEFTright- RIGHTright- ))
( LEFTleft+ SAMEback ( LEFTright- ))
( LEFTleft+ SAMEfront ( LEFTleft+ ))
( LEFTleft+ SAMEleft ( LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- ))
( LEFTleft+ SAMEright ( LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP ))
( LEFTleft- BACKback ( LEFTright+ ))
( LEFTleft- BACKfront ( LEFTleft- ))
( LEFTleft- BACKleft ( LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ ))
( LEFTleft- BACKright ( LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP ))
( LEFTleft- FRONTback ( BACKleft LEFTleft- RIGHTleft- ))
( LEFTleft- FRONTfront ( BACKright LEFTright+ RIGHTright+ ))
( LEFTleft- FRONTleft ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( LEFTleft- FRONTright ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTleft- LEFTback ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleft- LEFTfront ( BACKright FRONTleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleft- LEFTleft+ ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( LEFTleft- LEFTleft- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleft- LEFTleftA ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleft- LEFTright+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleft- LEFTright- ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( LEFTleft- LEFTrightP ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleft- RIGHTback ( BACKleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTleft- ))
( LEFTleft- RIGHTfront ( BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTleft- RIGHTleft+ ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( LEFTleft- RIGHTleft- ( BACKleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTleft- ))
( LEFTleft- RIGHTleftP ( BACKleft LEFTleft- RIGHTleft- ))
( LEFTleft- RIGHTright+ ( BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTleft- RIGHTright- ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTleft- RIGHTrightA ( BACKright LEFTright+ RIGHTright+ ))
( LEFTleft- SAMEback ( LEFTright+ ))
( LEFTleft- SAMEfront ( LEFTleft- ))
( LEFTleft- SAMEleft ( LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP ))
( LEFTleft- SAMEright ( LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ ))
( LEFTleftA BACKback ( LEFTrightP ))
( LEFTleftA BACKfront ( LEFTleftA ))
( LEFTleftA BACKleft ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTleftA BACKright ( LEFTfront LEFTleft- LEFTright- ))
( LEFTleftA FRONTback ( LEFTleftA ))
( LEFTleftA FRONTfront ( LEFTrightP ))
( LEFTleftA FRONTleft ( LEFTfront LEFTleft- LEFTright- ))
( LEFTleftA FRONTright ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTleftA LEFTback ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleftA LEFTfront ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleftA LEFTleft+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleftA LEFTleft- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleftA LEFTleftA ( BACKfront FRONTback LEFTrightP RIGHTleftP SAMEfront ))
( LEFTleftA LEFTright+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTleftA LEFTright- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTleftA LEFTrightP ( BACKback FRONTfront LEFTleftA RIGHTrightA SAMEback ))
( LEFTleftA RIGHTback ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTleftA RIGHTfront ( LEFTfront LEFTleft- LEFTright- ))
( LEFTleftA RIGHTleft+ ( LEFTfront LEFTleft- LEFTright- ))
( LEFTleftA RIGHTleft- ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTleftA RIGHTleftP ( LEFTleftA ))
( LEFTleftA RIGHTright+ ( LEFTfront LEFTleft- LEFTright- ))
( LEFTleftA RIGHTright- ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTleftA RIGHTrightA ( LEFTrightP ))
( LEFTleftA SAMEback ( LEFTrightP ))
( LEFTleftA SAMEfront ( LEFTleftA ))
( LEFTleftA SAMEleft ( LEFTfront LEFTleft- LEFTright- ))
( LEFTleftA SAMEright ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTright+ BACKback ( BACKleft LEFTleft- RIGHTleft- ))
( LEFTright+ BACKfront ( BACKright LEFTright+ RIGHTright+ ))
( LEFTright+ BACKleft ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( LEFTright+ BACKright ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTright+ FRONTback ( LEFTright+ ))
( LEFTright+ FRONTfront ( LEFTleft- ))
( LEFTright+ FRONTleft ( LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ ))
( LEFTright+ FRONTright ( LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP ))
( LEFTright+ LEFTback ( BACKleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTleft- ))
( LEFTright+ LEFTfront ( BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTright+ LEFTleft+ ( BACKleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTleft- ))
( LEFTright+ LEFTleft- ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( LEFTright+ LEFTleftA ( BACKleft LEFTleft- RIGHTleft- ))
( LEFTright+ LEFTright+ ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTright+ LEFTright- ( BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( LEFTright+ LEFTrightP ( BACKright LEFTright+ RIGHTright+ ))
( LEFTright+ RIGHTback ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTright+ RIGHTfront ( BACKright FRONTleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTright+ RIGHTleft+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTright+ RIGHTleft- ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( LEFTright+ RIGHTleftP ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTright+ RIGHTright+ ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( LEFTright+ RIGHTright- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTright+ RIGHTrightA ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTright+ SAMEback ( LEFTleft- ))
( LEFTright+ SAMEfront ( LEFTright+ ))
( LEFTright+ SAMEleft ( LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ ))
( LEFTright+ SAMEright ( LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP ))
( LEFTright- BACKback ( LEFTleft+ ))
( LEFTright- BACKfront ( LEFTright- ))
( LEFTright- BACKleft ( LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- ))
( LEFTright- BACKright ( LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP ))
( LEFTright- FRONTback ( FRONTright LEFTright- RIGHTright- ))
( LEFTright- FRONTfront ( FRONTleft LEFTleft+ RIGHTleft+ ))
( LEFTright- FRONTleft ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( LEFTright- FRONTright ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTright- LEFTback ( FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTright- LEFTfront ( FRONTleft LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTleft+ ))
( LEFTright- LEFTleft+ ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( LEFTright- LEFTleft- ( FRONTleft LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTleft+ ))
( LEFTright- LEFTleftA ( FRONTleft LEFTleft+ RIGHTleft+ ))
( LEFTright- LEFTright+ ( FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( LEFTright- LEFTright- ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( LEFTright- LEFTrightP ( FRONTright LEFTright- RIGHTright- ))
( LEFTright- RIGHTback ( BACKleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTright- RIGHTfront ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTright- RIGHTleft+ ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( LEFTright- RIGHTleft- ( BACKleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTright- RIGHTleftP ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTright- RIGHTright+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTright- RIGHTright- ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( LEFTright- RIGHTrightA ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTright- SAMEback ( LEFTleft+ ))
( LEFTright- SAMEfront ( LEFTright- ))
( LEFTright- SAMEleft ( LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP ))
( LEFTright- SAMEright ( LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- ))
( LEFTrightP BACKback ( LEFTleftA ))
( LEFTrightP BACKfront ( LEFTrightP ))
( LEFTrightP BACKleft ( LEFTfront LEFTleft- LEFTright- ))
( LEFTrightP BACKright ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTrightP FRONTback ( LEFTrightP ))
( LEFTrightP FRONTfront ( LEFTleftA ))
( LEFTrightP FRONTleft ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTrightP FRONTright ( LEFTfront LEFTleft- LEFTright- ))
( LEFTrightP LEFTback ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTrightP LEFTfront ( LEFTfront LEFTleft- LEFTright- ))
( LEFTrightP LEFTleft+ ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTrightP LEFTleft- ( LEFTfront LEFTleft- LEFTright- ))
( LEFTrightP LEFTleftA ( LEFTleftA ))
( LEFTrightP LEFTright+ ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTrightP LEFTright- ( LEFTfront LEFTleft- LEFTright- ))
( LEFTrightP LEFTrightP ( LEFTrightP ))
( LEFTrightP RIGHTback ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTrightP RIGHTfront ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTrightP RIGHTleft+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTrightP RIGHTleft- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTrightP RIGHTleftP ( BACKfront FRONTback LEFTrightP RIGHTleftP SAMEfront ))
( LEFTrightP RIGHTright+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( LEFTrightP RIGHTright- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( LEFTrightP RIGHTrightA ( BACKback FRONTfront LEFTleftA RIGHTrightA SAMEback ))
( LEFTrightP SAMEback ( LEFTleftA ))
( LEFTrightP SAMEfront ( LEFTrightP ))
( LEFTrightP SAMEleft ( LEFTback LEFTleft+ LEFTright+ ))
( LEFTrightP SAMEright ( LEFTfront LEFTleft- LEFTright- ))
( RIGHTback BACKback ( LEFTback RIGHTfront SAMEleft ))
( RIGHTback BACKfront ( LEFTfront RIGHTback SAMEright ))
( RIGHTback BACKleft ( LEFTleft+ LEFTleft- LEFTleftA RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( RIGHTback BACKright ( LEFTright+ LEFTright- LEFTrightP RIGHTleft+ RIGHTleft- RIGHTleftP SAMEfront SAMEleft SAMEright ))
( RIGHTback FRONTback ( RIGHTback ))
( RIGHTback FRONTfront ( RIGHTfront ))
( RIGHTback FRONTleft ( RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTback FRONTright ( RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTback LEFTback ( FRONTleft LEFTleft+ RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTback LEFTfront ( FRONTright LEFTright- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTback LEFTleft+ ( FRONTleft LEFTleft+ RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTback LEFTleft- ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTback LEFTleftA ( FRONTleft LEFTleft+ RIGHTleft+ ))
( RIGHTback LEFTright+ ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTback LEFTright- ( FRONTright LEFTright- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTback LEFTrightP ( FRONTright LEFTright- RIGHTright- ))
( RIGHTback RIGHTback ( BACKright LEFTright+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTback RIGHTfront ( BACKleft LEFTleft- RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTback RIGHTleft+ ( BACKleft LEFTleft- RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTback RIGHTleft- ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTback RIGHTleftP ( BACKleft LEFTleft- RIGHTleft- ))
( RIGHTback RIGHTright+ ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTback RIGHTright- ( BACKright LEFTright+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTback RIGHTrightA ( BACKright LEFTright+ RIGHTright+ ))
( RIGHTback SAMEback ( RIGHTfront ))
( RIGHTback SAMEfront ( RIGHTback ))
( RIGHTback SAMEleft ( RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTback SAMEright ( RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront BACKback ( RIGHTback ))
( RIGHTfront BACKfront ( RIGHTfront ))
( RIGHTfront BACKleft ( RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTfront BACKright ( RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront FRONTback ( LEFTback RIGHTfront SAMEleft ))
( RIGHTfront FRONTfront ( LEFTfront RIGHTback SAMEright ))
( RIGHTfront FRONTleft ( LEFTleft+ LEFTleft- LEFTleftA RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( RIGHTfront FRONTright ( LEFTright+ LEFTright- LEFTrightP RIGHTleft+ RIGHTleft- RIGHTleftP SAMEfront SAMEleft SAMEright ))
( RIGHTfront LEFTback ( BACKright LEFTright+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront LEFTfront ( BACKleft LEFTleft- RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTfront LEFTleft+ ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront LEFTleft- ( BACKleft LEFTleft- RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTfront LEFTleftA ( BACKleft LEFTleft- RIGHTleft- ))
( RIGHTfront LEFTright+ ( BACKright LEFTright+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront LEFTright- ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTfront LEFTrightP ( BACKright LEFTright+ RIGHTright+ ))
( RIGHTfront RIGHTback ( FRONTleft LEFTleft+ RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTfront RIGHTfront ( FRONTright LEFTright- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront RIGHTleft+ ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront RIGHTleft- ( FRONTleft LEFTleft+ RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTfront RIGHTleftP ( FRONTleft LEFTleft+ RIGHTleft+ ))
( RIGHTfront RIGHTright+ ( FRONTright LEFTright- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront RIGHTright- ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTfront RIGHTrightA ( FRONTright LEFTright- RIGHTright- ))
( RIGHTfront SAMEback ( RIGHTback ))
( RIGHTfront SAMEfront ( RIGHTfront ))
( RIGHTfront SAMEleft ( RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTfront SAMEright ( RIGHTleft+ RIGHTleft- RIGHTleftP ))
( RIGHTleft+ BACKback ( RIGHTright- ))
( RIGHTleft+ BACKfront ( RIGHTleft+ ))
( RIGHTleft+ BACKleft ( RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTleft+ BACKright ( RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft+ FRONTback ( FRONTleft LEFTleft+ RIGHTleft+ ))
( RIGHTleft+ FRONTfront ( FRONTright LEFTright- RIGHTright- ))
( RIGHTleft+ FRONTleft ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft+ FRONTright ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTleft+ LEFTback ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA SAMEleft ))
( RIGHTleft+ LEFTfront ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- SAMEright ))
( RIGHTleft+ LEFTleft+ ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( RIGHTleft+ LEFTleft- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- SAMEright ))
( RIGHTleft+ LEFTleftA ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTleft+ LEFTright+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA SAMEleft ))
( RIGHTleft+ LEFTright- ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( RIGHTleft+ LEFTrightP ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTleft+ RIGHTback ( FRONTleft LEFTleft+ RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTleft+ RIGHTfront ( FRONTright LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft+ RIGHTleft+ ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft+ RIGHTleft- ( FRONTleft LEFTleft+ RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTleft+ RIGHTleftP ( FRONTleft LEFTleft+ RIGHTleft+ ))
( RIGHTleft+ RIGHTright+ ( FRONTright LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft+ RIGHTright- ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTleft+ RIGHTrightA ( FRONTright LEFTright- RIGHTright- ))
( RIGHTleft+ SAMEback ( RIGHTright- ))
( RIGHTleft+ SAMEfront ( RIGHTleft+ ))
( RIGHTleft+ SAMEleft ( RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft+ SAMEright ( RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTleft- BACKback ( BACKright LEFTright+ RIGHTright+ ))
( RIGHTleft- BACKfront ( BACKleft LEFTleft- RIGHTleft- ))
( RIGHTleft- BACKleft ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft- BACKright ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTleft- FRONTback ( RIGHTleft- ))
( RIGHTleft- FRONTfront ( RIGHTright+ ))
( RIGHTleft- FRONTleft ( RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTleft- FRONTright ( RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft- LEFTback ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ SAMEleft ))
( RIGHTleft- LEFTfront ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEright ))
( RIGHTleft- LEFTleft+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ SAMEleft ))
( RIGHTleft- LEFTleft- ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( RIGHTleft- LEFTleftA ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTleft- LEFTright+ ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( RIGHTleft- LEFTright- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEright ))
( RIGHTleft- LEFTrightP ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTleft- RIGHTback ( BACKright LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft- RIGHTfront ( BACKleft LEFTleft- RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTleft- RIGHTleft+ ( BACKleft LEFTleft- RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTleft- RIGHTleft- ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft- RIGHTleftP ( BACKleft LEFTleft- RIGHTleft- ))
( RIGHTleft- RIGHTright+ ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTleft- RIGHTright- ( BACKright LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleft- RIGHTrightA ( BACKright LEFTright+ RIGHTright+ ))
( RIGHTleft- SAMEback ( RIGHTright+ ))
( RIGHTleft- SAMEfront ( RIGHTleft- ))
( RIGHTleft- SAMEleft ( RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTleft- SAMEright ( RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTleftP BACKback ( RIGHTrightA ))
( RIGHTleftP BACKfront ( RIGHTleftP ))
( RIGHTleftP BACKleft ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTleftP BACKright ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTleftP FRONTback ( RIGHTleftP ))
( RIGHTleftP FRONTfront ( RIGHTrightA ))
( RIGHTleftP FRONTleft ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTleftP FRONTright ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTleftP LEFTback ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTleftP LEFTfront ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTleftP LEFTleft+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTleftP LEFTleft- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTleftP LEFTleftA ( BACKback FRONTfront LEFTleftA RIGHTrightA SAMEback ))
( RIGHTleftP LEFTright+ ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTleftP LEFTright- ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTleftP LEFTrightP ( BACKfront FRONTback LEFTrightP RIGHTleftP SAMEfront ))
( RIGHTleftP RIGHTback ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTleftP RIGHTfront ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTleftP RIGHTleft+ ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTleftP RIGHTleft- ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTleftP RIGHTleftP ( RIGHTleftP ))
( RIGHTleftP RIGHTright+ ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTleftP RIGHTright- ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTleftP RIGHTrightA ( RIGHTrightA ))
( RIGHTleftP SAMEback ( RIGHTrightA ))
( RIGHTleftP SAMEfront ( RIGHTleftP ))
( RIGHTleftP SAMEleft ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTleftP SAMEright ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTright+ BACKback ( RIGHTleft- ))
( RIGHTright+ BACKfront ( RIGHTright+ ))
( RIGHTright+ BACKleft ( RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTright+ BACKright ( RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright+ FRONTback ( BACKright LEFTright+ RIGHTright+ ))
( RIGHTright+ FRONTfront ( BACKleft LEFTleft- RIGHTleft- ))
( RIGHTright+ FRONTleft ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright+ FRONTright ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTright+ LEFTback ( BACKright LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright+ LEFTfront ( BACKleft LEFTleft- RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTright+ LEFTleft+ ( BACKback BACKleft BACKright LEFTback LEFTleft+ LEFTleft- LEFTleftA LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright+ LEFTleft- ( BACKleft LEFTleft- RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTright+ LEFTleftA ( BACKleft LEFTleft- RIGHTleft- ))
( RIGHTright+ LEFTright+ ( BACKright LEFTright+ RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright+ LEFTright- ( BACKfront BACKleft BACKright LEFTfront LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTright+ LEFTrightP ( BACKright LEFTright+ RIGHTright+ ))
( RIGHTright+ RIGHTback ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ SAMEleft ))
( RIGHTright+ RIGHTfront ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEright ))
( RIGHTright+ RIGHTleft+ ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( RIGHTright+ RIGHTleft- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ SAMEleft ))
( RIGHTright+ RIGHTleftP ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTright+ RIGHTright+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEright ))
( RIGHTright+ RIGHTright- ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( RIGHTright+ RIGHTrightA ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTright+ SAMEback ( RIGHTleft- ))
( RIGHTright+ SAMEfront ( RIGHTright+ ))
( RIGHTright+ SAMEleft ( RIGHTback RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright+ SAMEright ( RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ ))
( RIGHTright- BACKback ( FRONTleft LEFTleft+ RIGHTleft+ ))
( RIGHTright- BACKfront ( FRONTright LEFTright- RIGHTright- ))
( RIGHTright- BACKleft ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright- BACKright ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTright- FRONTback ( RIGHTright- ))
( RIGHTright- FRONTfront ( RIGHTleft+ ))
( RIGHTright- FRONTleft ( RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTright- FRONTright ( RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright- LEFTback ( FRONTleft LEFTleft+ RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTright- LEFTfront ( FRONTright LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright- LEFTleft+ ( FRONTleft LEFTleft+ RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTright- LEFTleft- ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright- LEFTleftA ( FRONTleft LEFTleft+ RIGHTleft+ ))
( RIGHTright- LEFTright+ ( FRONTback FRONTleft FRONTright LEFTback LEFTleft+ LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTright- LEFTright- ( FRONTright LEFTright- RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTright- LEFTrightP ( FRONTright LEFTright- RIGHTright- ))
( RIGHTright- RIGHTback ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA SAMEleft ))
( RIGHTright- RIGHTfront ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- SAMEright ))
( RIGHTright- RIGHTleft+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- SAMEright ))
( RIGHTright- RIGHTleft- ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTleftA LEFTright+ LEFTright- RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTright+ RIGHTright- RIGHTrightA SAMEback SAMEleft SAMEright ))
( RIGHTright- RIGHTleftP ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTright- RIGHTright+ ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft+ LEFTleft- LEFTright+ LEFTright- LEFTrightP RIGHTback RIGHTfront RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright+ RIGHTright- SAMEfront SAMEleft SAMEright ))
( RIGHTright- RIGHTright- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA SAMEleft ))
( RIGHTright- RIGHTrightA ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTright- SAMEback ( RIGHTleft+ ))
( RIGHTright- SAMEfront ( RIGHTright- ))
( RIGHTright- SAMEleft ( RIGHTback RIGHTleft+ RIGHTleft- RIGHTleftP RIGHTright- ))
( RIGHTright- SAMEright ( RIGHTfront RIGHTleft+ RIGHTright+ RIGHTright- RIGHTrightA ))
( RIGHTrightA BACKback ( RIGHTleftP ))
( RIGHTrightA BACKfront ( RIGHTrightA ))
( RIGHTrightA BACKleft ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTrightA BACKright ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTrightA FRONTback ( RIGHTrightA ))
( RIGHTrightA FRONTfront ( RIGHTleftP ))
( RIGHTrightA FRONTleft ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTrightA FRONTright ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTrightA LEFTback ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTrightA LEFTfront ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTrightA LEFTleft+ ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTrightA LEFTleft- ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTrightA LEFTleftA ( RIGHTleftP ))
( RIGHTrightA LEFTright+ ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTrightA LEFTright- ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( RIGHTrightA LEFTrightP ( RIGHTrightA ))
( RIGHTrightA RIGHTback ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTrightA RIGHTfront ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTrightA RIGHTleft+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTrightA RIGHTleft- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTrightA RIGHTleftP ( BACKback FRONTfront LEFTleftA RIGHTrightA SAMEback ))
( RIGHTrightA RIGHTright+ ( BACKleft FRONTright LEFTfront LEFTleft- LEFTright- RIGHTback RIGHTleft- RIGHTright- SAMEright ))
( RIGHTrightA RIGHTright- ( BACKright FRONTleft LEFTback LEFTleft+ LEFTright+ RIGHTfront RIGHTleft+ RIGHTright+ SAMEleft ))
( RIGHTrightA RIGHTrightA ( BACKfront FRONTback LEFTrightP RIGHTleftP SAMEfront ))
( RIGHTrightA SAMEback ( RIGHTleftP ))
( RIGHTrightA SAMEfront ( RIGHTrightA ))
( RIGHTrightA SAMEleft ( RIGHTback RIGHTleft- RIGHTright- ))
( RIGHTrightA SAMEright ( RIGHTfront RIGHTleft+ RIGHTright+ ))
( SAMEback BACKback ( FRONTback ))
( SAMEback BACKfront ( FRONTfront ))
( SAMEback BACKleft ( FRONTleft ))
( SAMEback BACKright ( FRONTright ))
( SAMEback FRONTback ( BACKback ))
( SAMEback FRONTfront ( BACKfront ))
( SAMEback FRONTleft ( BACKleft ))
( SAMEback FRONTright ( BACKright ))
( SAMEback LEFTback ( RIGHTback ))
( SAMEback LEFTfront ( RIGHTfront ))
( SAMEback LEFTleft+ ( RIGHTleft- ))
( SAMEback LEFTleft- ( RIGHTleft+ ))
( SAMEback LEFTleftA ( RIGHTleftP ))
( SAMEback LEFTright+ ( RIGHTright- ))
( SAMEback LEFTright- ( RIGHTright+ ))
( SAMEback LEFTrightP ( RIGHTrightA ))
( SAMEback RIGHTback ( LEFTback ))
( SAMEback RIGHTfront ( LEFTfront ))
( SAMEback RIGHTleft+ ( LEFTleft- ))
( SAMEback RIGHTleft- ( LEFTleft+ ))
( SAMEback RIGHTleftP ( LEFTleftA ))
( SAMEback RIGHTright+ ( LEFTright- ))
( SAMEback RIGHTright- ( LEFTright+ ))
( SAMEback RIGHTrightA ( LEFTrightP ))
( SAMEback SAMEback ( SAMEfront ))
( SAMEback SAMEfront ( SAMEback ))
( SAMEback SAMEleft ( SAMEright ))
( SAMEback SAMEright ( SAMEleft ))
( SAMEfront BACKback ( BACKback ))
( SAMEfront BACKfront ( BACKfront ))
( SAMEfront BACKleft ( BACKleft ))
( SAMEfront BACKright ( BACKright ))
( SAMEfront FRONTback ( FRONTback ))
( SAMEfront FRONTfront ( FRONTfront ))
( SAMEfront FRONTleft ( FRONTleft ))
( SAMEfront FRONTright ( FRONTright ))
( SAMEfront LEFTback ( LEFTback ))
( SAMEfront LEFTfront ( LEFTfront ))
( SAMEfront LEFTleft+ ( LEFTleft+ ))
( SAMEfront LEFTleft- ( LEFTleft- ))
( SAMEfront LEFTleftA ( LEFTleftA ))
( SAMEfront LEFTright+ ( LEFTright+ ))
( SAMEfront LEFTright- ( LEFTright- ))
( SAMEfront LEFTrightP ( LEFTrightP ))
( SAMEfront RIGHTback ( RIGHTback ))
( SAMEfront RIGHTfront ( RIGHTfront ))
( SAMEfront RIGHTleft+ ( RIGHTleft+ ))
( SAMEfront RIGHTleft- ( RIGHTleft- ))
( SAMEfront RIGHTleftP ( RIGHTleftP ))
( SAMEfront RIGHTright+ ( RIGHTright+ ))
( SAMEfront RIGHTright- ( RIGHTright- ))
( SAMEfront RIGHTrightA ( RIGHTrightA ))
( SAMEfront SAMEback ( SAMEback ))
( SAMEfront SAMEfront ( SAMEfront ))
( SAMEfront SAMEleft ( SAMEleft ))
( SAMEfront SAMEright ( SAMEright ))
( SAMEleft BACKback ( RIGHTback ))
( SAMEleft BACKfront ( RIGHTfront ))
( SAMEleft BACKleft ( RIGHTleft+ RIGHTleft- RIGHTleftP ))
( SAMEleft BACKright ( RIGHTright+ RIGHTright- RIGHTrightA ))
( SAMEleft FRONTback ( LEFTback ))
( SAMEleft FRONTfront ( LEFTfront ))
( SAMEleft FRONTleft ( LEFTleft+ LEFTleft- LEFTleftA ))
( SAMEleft FRONTright ( LEFTright+ LEFTright- LEFTrightP ))
( SAMEleft LEFTback ( BACKback LEFTback RIGHTback ))
( SAMEleft LEFTfront ( BACKfront LEFTfront RIGHTfront ))
( SAMEleft LEFTleft+ ( BACKleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft- ))
( SAMEleft LEFTleft- ( BACKleft LEFTleft- RIGHTleft+ RIGHTleft- RIGHTleftP ))
( SAMEleft LEFTleftA ( BACKleft LEFTleft- RIGHTleft- ))
( SAMEleft LEFTright+ ( BACKright LEFTright+ RIGHTright+ RIGHTright- RIGHTrightA ))
( SAMEleft LEFTright- ( BACKright LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( SAMEleft LEFTrightP ( BACKright LEFTright+ RIGHTright+ ))
( SAMEleft RIGHTback ( FRONTback LEFTback RIGHTback ))
( SAMEleft RIGHTfront ( FRONTfront LEFTfront RIGHTfront ))
( SAMEleft RIGHTleft+ ( FRONTleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft+ ))
( SAMEleft RIGHTleft- ( FRONTleft LEFTleft+ RIGHTleft+ RIGHTleft- RIGHTleftP ))
( SAMEleft RIGHTleftP ( FRONTleft LEFTleft+ RIGHTleft+ ))
( SAMEleft RIGHTright+ ( FRONTright LEFTright- RIGHTright+ RIGHTright- RIGHTrightA ))
( SAMEleft RIGHTright- ( FRONTright LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( SAMEleft RIGHTrightA ( FRONTright LEFTright- RIGHTright- ))
( SAMEleft SAMEback ( SAMEright ))
( SAMEleft SAMEfront ( SAMEleft ))
( SAMEleft SAMEleft ( SAMEback SAMEleft SAMEright ))
( SAMEleft SAMEright ( SAMEfront SAMEleft SAMEright ))
( SAMEright BACKback ( LEFTback ))
( SAMEright BACKfront ( LEFTfront ))
( SAMEright BACKleft ( LEFTleft+ LEFTleft- LEFTleftA ))
( SAMEright BACKright ( LEFTright+ LEFTright- LEFTrightP ))
( SAMEright FRONTback ( RIGHTback ))
( SAMEright FRONTfront ( RIGHTfront ))
( SAMEright FRONTleft ( RIGHTleft+ RIGHTleft- RIGHTleftP ))
( SAMEright FRONTright ( RIGHTright+ RIGHTright- RIGHTrightA ))
( SAMEright LEFTback ( FRONTback LEFTback RIGHTback ))
( SAMEright LEFTfront ( FRONTfront LEFTfront RIGHTfront ))
( SAMEright LEFTleft+ ( FRONTleft LEFTleft+ RIGHTleft+ RIGHTleft- RIGHTleftP ))
( SAMEright LEFTleft- ( FRONTleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft+ ))
( SAMEright LEFTleftA ( FRONTleft LEFTleft+ RIGHTleft+ ))
( SAMEright LEFTright+ ( FRONTright LEFTright+ LEFTright- LEFTrightP RIGHTright- ))
( SAMEright LEFTright- ( FRONTright LEFTright- RIGHTright+ RIGHTright- RIGHTrightA ))
( SAMEright LEFTrightP ( FRONTright LEFTright- RIGHTright- ))
( SAMEright RIGHTback ( BACKback LEFTback RIGHTback ))
( SAMEright RIGHTfront ( BACKfront LEFTfront RIGHTfront ))
( SAMEright RIGHTleft+ ( BACKleft LEFTleft- RIGHTleft+ RIGHTleft- RIGHTleftP ))
( SAMEright RIGHTleft- ( BACKleft LEFTleft+ LEFTleft- LEFTleftA RIGHTleft- ))
( SAMEright RIGHTleftP ( BACKleft LEFTleft- RIGHTleft- ))
( SAMEright RIGHTright+ ( BACKright LEFTright+ LEFTright- LEFTrightP RIGHTright+ ))
( SAMEright RIGHTright- ( BACKright LEFTright+ RIGHTright+ RIGHTright- RIGHTrightA ))
( SAMEright RIGHTrightA ( BACKright LEFTright+ RIGHTright+ ))
( SAMEright SAMEback ( SAMEleft ))
( SAMEright SAMEfront ( SAMEright ))
( SAMEright SAMEleft ( SAMEfront SAMEleft SAMEright ))
( SAMEright SAMEright ( SAMEback SAMEleft SAMEright ))
	)
)

