(def-calculus "Dipole relation algebra fine projected (DRA_op)"
	:arity			:binary 
	:basis-entity		:2d-oriented-point
	:parametric?		nil
	:identity-relation	SAMEfront
	:converse-operation (
( BACKback BACKback )
( BACKfront FRONTback )
( BACKleft LEFTback )
( BACKright RIGHTback )
( FRONTback BACKfront )
( FRONTfront FRONTfront )
( FRONTleft LEFTfront )
( FRONTright RIGHTfront )
( LEFTback BACKleft )
( LEFTfront FRONTleft )
( LEFTleft LEFTleft )
( LEFTright RIGHTleft )
( RIGHTback BACKright )
( RIGHTfront FRONTright )
( RIGHTleft LEFTright )
( RIGHTright RIGHTright )
( SAMEback SAMEback )
( SAMEfront SAMEfront )
( SAMEleft SAMEright )
( SAMEright SAMEleft )
	)
	:base-relations
		( BACKback BACKfront BACKleft BACKright FRONTback FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEback SAMEfront SAMEleft SAMEright )
	:composition-operation
	(
( BACKback BACKback ( BACKfront FRONTback SAMEfront ))
( BACKback BACKfront ( BACKback FRONTfront SAMEback ))
( BACKback BACKleft ( BACKright FRONTleft SAMEleft ))
( BACKback BACKright ( BACKleft FRONTright SAMEright ))
( BACKback FRONTback ( BACKback ))
( BACKback FRONTfront ( BACKfront ))
( BACKback FRONTleft ( BACKleft ))
( BACKback FRONTright ( BACKright ))
( BACKback LEFTback ( RIGHTleft ))
( BACKback LEFTfront ( RIGHTright ))
( BACKback LEFTleft ( RIGHTfront RIGHTleft RIGHTright ))
( BACKback LEFTright ( RIGHTback RIGHTleft RIGHTright ))
( BACKback RIGHTback ( LEFTright ))
( BACKback RIGHTfront ( LEFTleft ))
( BACKback RIGHTleft ( LEFTback LEFTleft LEFTright ))
( BACKback RIGHTright ( LEFTfront LEFTleft LEFTright ))
( BACKback SAMEback ( BACKfront ))
( BACKback SAMEfront ( BACKback ))
( BACKback SAMEleft ( BACKleft ))
( BACKback SAMEright ( BACKright ))
( BACKfront BACKback ( BACKback ))
( BACKfront BACKfront ( BACKfront ))
( BACKfront BACKleft ( BACKleft ))
( BACKfront BACKright ( BACKright ))
( BACKfront FRONTback ( BACKfront FRONTback SAMEfront ))
( BACKfront FRONTfront ( BACKback FRONTfront SAMEback ))
( BACKfront FRONTleft ( BACKright FRONTleft SAMEleft ))
( BACKfront FRONTright ( BACKleft FRONTright SAMEright ))
( BACKfront LEFTback ( LEFTright ))
( BACKfront LEFTfront ( LEFTleft ))
( BACKfront LEFTleft ( LEFTback LEFTleft LEFTright ))
( BACKfront LEFTright ( LEFTfront LEFTleft LEFTright ))
( BACKfront RIGHTback ( RIGHTleft ))
( BACKfront RIGHTfront ( RIGHTright ))
( BACKfront RIGHTleft ( RIGHTfront RIGHTleft RIGHTright ))
( BACKfront RIGHTright ( RIGHTback RIGHTleft RIGHTright ))
( BACKfront SAMEback ( BACKback ))
( BACKfront SAMEfront ( BACKfront ))
( BACKfront SAMEleft ( BACKright ))
( BACKfront SAMEright ( BACKleft ))
( BACKleft BACKback ( LEFTright ))
( BACKleft BACKfront ( LEFTleft ))
( BACKleft BACKleft ( LEFTback LEFTleft LEFTright ))
( BACKleft BACKright ( LEFTfront LEFTleft LEFTright ))
( BACKleft FRONTback ( RIGHTleft ))
( BACKleft FRONTfront ( RIGHTright ))
( BACKleft FRONTleft ( RIGHTfront RIGHTleft RIGHTright ))
( BACKleft FRONTright ( RIGHTback RIGHTleft RIGHTright ))
( BACKleft LEFTback ( BACKfront FRONTback LEFTright RIGHTleft SAMEfront ))
( BACKleft LEFTfront ( BACKback FRONTfront LEFTleft RIGHTright SAMEback ))
( BACKleft LEFTleft ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( BACKleft LEFTright ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( BACKleft RIGHTback ( BACKback LEFTright RIGHTleft ))
( BACKleft RIGHTfront ( BACKfront LEFTleft RIGHTright ))
( BACKleft RIGHTleft ( BACKleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( BACKleft RIGHTright ( BACKright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( BACKleft SAMEback ( BACKright ))
( BACKleft SAMEfront ( BACKleft ))
( BACKleft SAMEleft ( BACKfront BACKleft BACKright ))
( BACKleft SAMEright ( BACKback BACKleft BACKright ))
( BACKright BACKback ( RIGHTleft ))
( BACKright BACKfront ( RIGHTright ))
( BACKright BACKleft ( RIGHTfront RIGHTleft RIGHTright ))
( BACKright BACKright ( RIGHTback RIGHTleft RIGHTright ))
( BACKright FRONTback ( LEFTright ))
( BACKright FRONTfront ( LEFTleft ))
( BACKright FRONTleft ( LEFTback LEFTleft LEFTright ))
( BACKright FRONTright ( LEFTfront LEFTleft LEFTright ))
( BACKright LEFTback ( BACKback LEFTright RIGHTleft ))
( BACKright LEFTfront ( BACKfront LEFTleft RIGHTright ))
( BACKright LEFTleft ( BACKleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( BACKright LEFTright ( BACKright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( BACKright RIGHTback ( BACKfront FRONTback LEFTright RIGHTleft SAMEfront ))
( BACKright RIGHTfront ( BACKback FRONTfront LEFTleft RIGHTright SAMEback ))
( BACKright RIGHTleft ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( BACKright RIGHTright ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( BACKright SAMEback ( BACKleft ))
( BACKright SAMEfront ( BACKright ))
( BACKright SAMEleft ( BACKback BACKleft BACKright ))
( BACKright SAMEright ( BACKfront BACKleft BACKright ))
( FRONTback BACKback ( BACKback FRONTfront SAMEback ))
( FRONTback BACKfront ( BACKfront FRONTback SAMEfront ))
( FRONTback BACKleft ( BACKleft FRONTright SAMEright ))
( FRONTback BACKright ( BACKright FRONTleft SAMEleft ))
( FRONTback FRONTback ( FRONTback ))
( FRONTback FRONTfront ( FRONTfront ))
( FRONTback FRONTleft ( FRONTleft ))
( FRONTback FRONTright ( FRONTright ))
( FRONTback LEFTback ( LEFTleft ))
( FRONTback LEFTfront ( LEFTright ))
( FRONTback LEFTleft ( LEFTfront LEFTleft LEFTright ))
( FRONTback LEFTright ( LEFTback LEFTleft LEFTright ))
( FRONTback RIGHTback ( RIGHTright ))
( FRONTback RIGHTfront ( RIGHTleft ))
( FRONTback RIGHTleft ( RIGHTback RIGHTleft RIGHTright ))
( FRONTback RIGHTright ( RIGHTfront RIGHTleft RIGHTright ))
( FRONTback SAMEback ( FRONTfront ))
( FRONTback SAMEfront ( FRONTback ))
( FRONTback SAMEleft ( FRONTleft ))
( FRONTback SAMEright ( FRONTright ))
( FRONTfront BACKback ( FRONTback ))
( FRONTfront BACKfront ( FRONTfront ))
( FRONTfront BACKleft ( FRONTleft ))
( FRONTfront BACKright ( FRONTright ))
( FRONTfront FRONTback ( BACKback FRONTfront SAMEback ))
( FRONTfront FRONTfront ( BACKfront FRONTback SAMEfront ))
( FRONTfront FRONTleft ( BACKleft FRONTright SAMEright ))
( FRONTfront FRONTright ( BACKright FRONTleft SAMEleft ))
( FRONTfront LEFTback ( RIGHTright ))
( FRONTfront LEFTfront ( RIGHTleft ))
( FRONTfront LEFTleft ( RIGHTback RIGHTleft RIGHTright ))
( FRONTfront LEFTright ( RIGHTfront RIGHTleft RIGHTright ))
( FRONTfront RIGHTback ( LEFTleft ))
( FRONTfront RIGHTfront ( LEFTright ))
( FRONTfront RIGHTleft ( LEFTfront LEFTleft LEFTright ))
( FRONTfront RIGHTright ( LEFTback LEFTleft LEFTright ))
( FRONTfront SAMEback ( FRONTback ))
( FRONTfront SAMEfront ( FRONTfront ))
( FRONTfront SAMEleft ( FRONTright ))
( FRONTfront SAMEright ( FRONTleft ))
( FRONTleft BACKback ( RIGHTright ))
( FRONTleft BACKfront ( RIGHTleft ))
( FRONTleft BACKleft ( RIGHTback RIGHTleft RIGHTright ))
( FRONTleft BACKright ( RIGHTfront RIGHTleft RIGHTright ))
( FRONTleft FRONTback ( LEFTleft ))
( FRONTleft FRONTfront ( LEFTright ))
( FRONTleft FRONTleft ( LEFTfront LEFTleft LEFTright ))
( FRONTleft FRONTright ( LEFTback LEFTleft LEFTright ))
( FRONTleft LEFTback ( BACKback FRONTfront LEFTleft RIGHTright SAMEback ))
( FRONTleft LEFTfront ( BACKfront FRONTback LEFTright RIGHTleft SAMEfront ))
( FRONTleft LEFTleft ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( FRONTleft LEFTright ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( FRONTleft RIGHTback ( FRONTback LEFTleft RIGHTright ))
( FRONTleft RIGHTfront ( FRONTfront LEFTright RIGHTleft ))
( FRONTleft RIGHTleft ( FRONTleft LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( FRONTleft RIGHTright ( FRONTright LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( FRONTleft SAMEback ( FRONTright ))
( FRONTleft SAMEfront ( FRONTleft ))
( FRONTleft SAMEleft ( FRONTfront FRONTleft FRONTright ))
( FRONTleft SAMEright ( FRONTback FRONTleft FRONTright ))
( FRONTright BACKback ( LEFTleft ))
( FRONTright BACKfront ( LEFTright ))
( FRONTright BACKleft ( LEFTfront LEFTleft LEFTright ))
( FRONTright BACKright ( LEFTback LEFTleft LEFTright ))
( FRONTright FRONTback ( RIGHTright ))
( FRONTright FRONTfront ( RIGHTleft ))
( FRONTright FRONTleft ( RIGHTback RIGHTleft RIGHTright ))
( FRONTright FRONTright ( RIGHTfront RIGHTleft RIGHTright ))
( FRONTright LEFTback ( FRONTback LEFTleft RIGHTright ))
( FRONTright LEFTfront ( FRONTfront LEFTright RIGHTleft ))
( FRONTright LEFTleft ( FRONTleft LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( FRONTright LEFTright ( FRONTright LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( FRONTright RIGHTback ( BACKback FRONTfront LEFTleft RIGHTright SAMEback ))
( FRONTright RIGHTfront ( BACKfront FRONTback LEFTright RIGHTleft SAMEfront ))
( FRONTright RIGHTleft ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( FRONTright RIGHTright ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( FRONTright SAMEback ( FRONTleft ))
( FRONTright SAMEfront ( FRONTright ))
( FRONTright SAMEleft ( FRONTback FRONTleft FRONTright ))
( FRONTright SAMEright ( FRONTfront FRONTleft FRONTright ))
( LEFTback BACKback ( LEFTfront RIGHTback SAMEright ))
( LEFTback BACKfront ( LEFTback RIGHTfront SAMEleft ))
( LEFTback BACKleft ( LEFTright RIGHTleft SAMEfront SAMEleft SAMEright ))
( LEFTback BACKright ( LEFTleft RIGHTright SAMEback SAMEleft SAMEright ))
( LEFTback FRONTback ( LEFTback ))
( LEFTback FRONTfront ( LEFTfront ))
( LEFTback FRONTleft ( LEFTleft ))
( LEFTback FRONTright ( LEFTright ))
( LEFTback LEFTback ( BACKleft LEFTleft RIGHTleft ))
( LEFTback LEFTfront ( BACKright LEFTright RIGHTright ))
( LEFTback LEFTleft ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTback LEFTright ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTback RIGHTback ( FRONTright LEFTright RIGHTright ))
( LEFTback RIGHTfront ( FRONTleft LEFTleft RIGHTleft ))
( LEFTback RIGHTleft ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTback RIGHTright ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTback SAMEback ( LEFTfront ))
( LEFTback SAMEfront ( LEFTback ))
( LEFTback SAMEleft ( LEFTleft ))
( LEFTback SAMEright ( LEFTright ))
( LEFTfront BACKback ( LEFTback ))
( LEFTfront BACKfront ( LEFTfront ))
( LEFTfront BACKleft ( LEFTleft ))
( LEFTfront BACKright ( LEFTright ))
( LEFTfront FRONTback ( LEFTfront RIGHTback SAMEright ))
( LEFTfront FRONTfront ( LEFTback RIGHTfront SAMEleft ))
( LEFTfront FRONTleft ( LEFTright RIGHTleft SAMEfront SAMEleft SAMEright ))
( LEFTfront FRONTright ( LEFTleft RIGHTright SAMEback SAMEleft SAMEright ))
( LEFTfront LEFTback ( FRONTright LEFTright RIGHTright ))
( LEFTfront LEFTfront ( FRONTleft LEFTleft RIGHTleft ))
( LEFTfront LEFTleft ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTfront LEFTright ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTfront RIGHTback ( BACKleft LEFTleft RIGHTleft ))
( LEFTfront RIGHTfront ( BACKright LEFTright RIGHTright ))
( LEFTfront RIGHTleft ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTfront RIGHTright ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTfront SAMEback ( LEFTback ))
( LEFTfront SAMEfront ( LEFTfront ))
( LEFTfront SAMEleft ( LEFTright ))
( LEFTfront SAMEright ( LEFTleft ))
( LEFTleft BACKback ( FRONTright LEFTright RIGHTright ))
( LEFTleft BACKfront ( FRONTleft LEFTleft RIGHTleft ))
( LEFTleft BACKleft ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTleft BACKright ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTleft FRONTback ( BACKleft LEFTleft RIGHTleft ))
( LEFTleft FRONTfront ( BACKright LEFTright RIGHTright ))
( LEFTleft FRONTleft ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTleft FRONTright ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTleft LEFTback ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( LEFTleft LEFTfront ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( LEFTleft LEFTleft ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEfront SAMEleft SAMEright ))
( LEFTleft LEFTright ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEback SAMEleft SAMEright ))
( LEFTleft RIGHTback ( BACKleft FRONTright LEFTback LEFTleft LEFTright RIGHTleft RIGHTright ))
( LEFTleft RIGHTfront ( BACKright FRONTleft LEFTfront LEFTleft LEFTright RIGHTleft RIGHTright ))
( LEFTleft RIGHTleft ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( LEFTleft RIGHTright ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( LEFTleft SAMEback ( LEFTright ))
( LEFTleft SAMEfront ( LEFTleft ))
( LEFTleft SAMEleft ( LEFTfront LEFTleft LEFTright ))
( LEFTleft SAMEright ( LEFTback LEFTleft LEFTright ))
( LEFTright BACKback ( BACKleft LEFTleft RIGHTleft ))
( LEFTright BACKfront ( BACKright LEFTright RIGHTright ))
( LEFTright BACKleft ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTright BACKright ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTright FRONTback ( FRONTright LEFTright RIGHTright ))
( LEFTright FRONTfront ( FRONTleft LEFTleft RIGHTleft ))
( LEFTright FRONTleft ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( LEFTright FRONTright ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( LEFTright LEFTback ( BACKleft FRONTright LEFTback LEFTleft LEFTright RIGHTleft RIGHTright ))
( LEFTright LEFTfront ( BACKright FRONTleft LEFTfront LEFTleft LEFTright RIGHTleft RIGHTright ))
( LEFTright LEFTleft ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( LEFTright LEFTright ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( LEFTright RIGHTback ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( LEFTright RIGHTfront ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( LEFTright RIGHTleft ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEfront SAMEleft SAMEright ))
( LEFTright RIGHTright ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEback SAMEleft SAMEright ))
( LEFTright SAMEback ( LEFTleft ))
( LEFTright SAMEfront ( LEFTright ))
( LEFTright SAMEleft ( LEFTback LEFTleft LEFTright ))
( LEFTright SAMEright ( LEFTfront LEFTleft LEFTright ))
( RIGHTback BACKback ( LEFTback RIGHTfront SAMEleft ))
( RIGHTback BACKfront ( LEFTfront RIGHTback SAMEright ))
( RIGHTback BACKleft ( LEFTleft RIGHTright SAMEback SAMEleft SAMEright ))
( RIGHTback BACKright ( LEFTright RIGHTleft SAMEfront SAMEleft SAMEright ))
( RIGHTback FRONTback ( RIGHTback ))
( RIGHTback FRONTfront ( RIGHTfront ))
( RIGHTback FRONTleft ( RIGHTleft ))
( RIGHTback FRONTright ( RIGHTright ))
( RIGHTback LEFTback ( FRONTleft LEFTleft RIGHTleft ))
( RIGHTback LEFTfront ( FRONTright LEFTright RIGHTright ))
( RIGHTback LEFTleft ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTback LEFTright ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTback RIGHTback ( BACKright LEFTright RIGHTright ))
( RIGHTback RIGHTfront ( BACKleft LEFTleft RIGHTleft ))
( RIGHTback RIGHTleft ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTback RIGHTright ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTback SAMEback ( RIGHTfront ))
( RIGHTback SAMEfront ( RIGHTback ))
( RIGHTback SAMEleft ( RIGHTleft ))
( RIGHTback SAMEright ( RIGHTright ))
( RIGHTfront BACKback ( RIGHTback ))
( RIGHTfront BACKfront ( RIGHTfront ))
( RIGHTfront BACKleft ( RIGHTleft ))
( RIGHTfront BACKright ( RIGHTright ))
( RIGHTfront FRONTback ( LEFTback RIGHTfront SAMEleft ))
( RIGHTfront FRONTfront ( LEFTfront RIGHTback SAMEright ))
( RIGHTfront FRONTleft ( LEFTleft RIGHTright SAMEback SAMEleft SAMEright ))
( RIGHTfront FRONTright ( LEFTright RIGHTleft SAMEfront SAMEleft SAMEright ))
( RIGHTfront LEFTback ( BACKright LEFTright RIGHTright ))
( RIGHTfront LEFTfront ( BACKleft LEFTleft RIGHTleft ))
( RIGHTfront LEFTleft ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTfront LEFTright ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTfront RIGHTback ( FRONTleft LEFTleft RIGHTleft ))
( RIGHTfront RIGHTfront ( FRONTright LEFTright RIGHTright ))
( RIGHTfront RIGHTleft ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTfront RIGHTright ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTfront SAMEback ( RIGHTback ))
( RIGHTfront SAMEfront ( RIGHTfront ))
( RIGHTfront SAMEleft ( RIGHTright ))
( RIGHTfront SAMEright ( RIGHTleft ))
( RIGHTleft BACKback ( BACKright LEFTright RIGHTright ))
( RIGHTleft BACKfront ( BACKleft LEFTleft RIGHTleft ))
( RIGHTleft BACKleft ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTleft BACKright ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTleft FRONTback ( FRONTleft LEFTleft RIGHTleft ))
( RIGHTleft FRONTfront ( FRONTright LEFTright RIGHTright ))
( RIGHTleft FRONTleft ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTleft FRONTright ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTleft LEFTback ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( RIGHTleft LEFTfront ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( RIGHTleft LEFTleft ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEback SAMEleft SAMEright ))
( RIGHTleft LEFTright ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEfront SAMEleft SAMEright ))
( RIGHTleft RIGHTback ( BACKright FRONTleft LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTleft RIGHTfront ( BACKleft FRONTright LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTleft RIGHTleft ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( RIGHTleft RIGHTright ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( RIGHTleft SAMEback ( RIGHTright ))
( RIGHTleft SAMEfront ( RIGHTleft ))
( RIGHTleft SAMEleft ( RIGHTfront RIGHTleft RIGHTright ))
( RIGHTleft SAMEright ( RIGHTback RIGHTleft RIGHTright ))
( RIGHTright BACKback ( FRONTleft LEFTleft RIGHTleft ))
( RIGHTright BACKfront ( FRONTright LEFTright RIGHTright ))
( RIGHTright BACKleft ( FRONTfront FRONTleft FRONTright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTright BACKright ( FRONTback FRONTleft FRONTright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTright FRONTback ( BACKright LEFTright RIGHTright ))
( RIGHTright FRONTfront ( BACKleft LEFTleft RIGHTleft ))
( RIGHTright FRONTleft ( BACKback BACKleft BACKright LEFTback LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTright FRONTright ( BACKfront BACKleft BACKright LEFTfront LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTright LEFTback ( BACKright FRONTleft LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright ))
( RIGHTright LEFTfront ( BACKleft FRONTright LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright ))
( RIGHTright LEFTleft ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( RIGHTright LEFTright ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright ))
( RIGHTright RIGHTback ( BACKright FRONTleft LEFTback LEFTleft LEFTright RIGHTfront RIGHTleft RIGHTright SAMEleft ))
( RIGHTright RIGHTfront ( BACKleft FRONTright LEFTfront LEFTleft LEFTright RIGHTback RIGHTleft RIGHTright SAMEright ))
( RIGHTright RIGHTleft ( BACKback BACKleft BACKright FRONTfront FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEback SAMEleft SAMEright ))
( RIGHTright RIGHTright ( BACKfront BACKleft BACKright FRONTback FRONTleft FRONTright LEFTback LEFTfront LEFTleft LEFTright RIGHTback RIGHTfront RIGHTleft RIGHTright SAMEfront SAMEleft SAMEright ))
( RIGHTright SAMEback ( RIGHTleft ))
( RIGHTright SAMEfront ( RIGHTright ))
( RIGHTright SAMEleft ( RIGHTback RIGHTleft RIGHTright ))
( RIGHTright SAMEright ( RIGHTfront RIGHTleft RIGHTright ))
( SAMEback BACKback ( FRONTback ))
( SAMEback BACKfront ( FRONTfront ))
( SAMEback BACKleft ( FRONTleft ))
( SAMEback BACKright ( FRONTright ))
( SAMEback FRONTback ( BACKback ))
( SAMEback FRONTfront ( BACKfront ))
( SAMEback FRONTleft ( BACKleft ))
( SAMEback FRONTright ( BACKright ))
( SAMEback LEFTback ( RIGHTback ))
( SAMEback LEFTfront ( RIGHTfront ))
( SAMEback LEFTleft ( RIGHTleft ))
( SAMEback LEFTright ( RIGHTright ))
( SAMEback RIGHTback ( LEFTback ))
( SAMEback RIGHTfront ( LEFTfront ))
( SAMEback RIGHTleft ( LEFTleft ))
( SAMEback RIGHTright ( LEFTright ))
( SAMEback SAMEback ( SAMEfront ))
( SAMEback SAMEfront ( SAMEback ))
( SAMEback SAMEleft ( SAMEright ))
( SAMEback SAMEright ( SAMEleft ))
( SAMEfront BACKback ( BACKback ))
( SAMEfront BACKfront ( BACKfront ))
( SAMEfront BACKleft ( BACKleft ))
( SAMEfront BACKright ( BACKright ))
( SAMEfront FRONTback ( FRONTback ))
( SAMEfront FRONTfront ( FRONTfront ))
( SAMEfront FRONTleft ( FRONTleft ))
( SAMEfront FRONTright ( FRONTright ))
( SAMEfront LEFTback ( LEFTback ))
( SAMEfront LEFTfront ( LEFTfront ))
( SAMEfront LEFTleft ( LEFTleft ))
( SAMEfront LEFTright ( LEFTright ))
( SAMEfront RIGHTback ( RIGHTback ))
( SAMEfront RIGHTfront ( RIGHTfront ))
( SAMEfront RIGHTleft ( RIGHTleft ))
( SAMEfront RIGHTright ( RIGHTright ))
( SAMEfront SAMEback ( SAMEback ))
( SAMEfront SAMEfront ( SAMEfront ))
( SAMEfront SAMEleft ( SAMEleft ))
( SAMEfront SAMEright ( SAMEright ))
( SAMEleft BACKback ( RIGHTback ))
( SAMEleft BACKfront ( RIGHTfront ))
( SAMEleft BACKleft ( RIGHTleft ))
( SAMEleft BACKright ( RIGHTright ))
( SAMEleft FRONTback ( LEFTback ))
( SAMEleft FRONTfront ( LEFTfront ))
( SAMEleft FRONTleft ( LEFTleft ))
( SAMEleft FRONTright ( LEFTright ))
( SAMEleft LEFTback ( BACKback LEFTback RIGHTback ))
( SAMEleft LEFTfront ( BACKfront LEFTfront RIGHTfront ))
( SAMEleft LEFTleft ( BACKleft LEFTleft RIGHTleft ))
( SAMEleft LEFTright ( BACKright LEFTright RIGHTright ))
( SAMEleft RIGHTback ( FRONTback LEFTback RIGHTback ))
( SAMEleft RIGHTfront ( FRONTfront LEFTfront RIGHTfront ))
( SAMEleft RIGHTleft ( FRONTleft LEFTleft RIGHTleft ))
( SAMEleft RIGHTright ( FRONTright LEFTright RIGHTright ))
( SAMEleft SAMEback ( SAMEright ))
( SAMEleft SAMEfront ( SAMEleft ))
( SAMEleft SAMEleft ( SAMEback SAMEleft SAMEright ))
( SAMEleft SAMEright ( SAMEfront SAMEleft SAMEright ))
( SAMEright BACKback ( LEFTback ))
( SAMEright BACKfront ( LEFTfront ))
( SAMEright BACKleft ( LEFTleft ))
( SAMEright BACKright ( LEFTright ))
( SAMEright FRONTback ( RIGHTback ))
( SAMEright FRONTfront ( RIGHTfront ))
( SAMEright FRONTleft ( RIGHTleft ))
( SAMEright FRONTright ( RIGHTright ))
( SAMEright LEFTback ( FRONTback LEFTback RIGHTback ))
( SAMEright LEFTfront ( FRONTfront LEFTfront RIGHTfront ))
( SAMEright LEFTleft ( FRONTleft LEFTleft RIGHTleft ))
( SAMEright LEFTright ( FRONTright LEFTright RIGHTright ))
( SAMEright RIGHTback ( BACKback LEFTback RIGHTback ))
( SAMEright RIGHTfront ( BACKfront LEFTfront RIGHTfront ))
( SAMEright RIGHTleft ( BACKleft LEFTleft RIGHTleft ))
( SAMEright RIGHTright ( BACKright LEFTright RIGHTright ))
( SAMEright SAMEback ( SAMEleft ))
( SAMEright SAMEfront ( SAMEright ))
( SAMEright SAMEleft ( SAMEfront SAMEleft SAMEright ))
( SAMEright SAMEright ( SAMEback SAMEleft SAMEright ))
	)
)

