;;;
;;; Dipole relation algebra coarse
;;;

(def-calculus "Dipole relation algebra coarse (DRA-24)"
    :arity             :binary
    :basis-entity      :dipole
    :parametric?       nil
    :consistency       :unknown
    :identity-relation sese
    :qualifier         (lambda (a b)
                         (destructuring-bind (asx asy aex aey) a
                           (destructuring-bind (bsx bsy bex bey) b
                             (flet ((ensure-dra-rel (r)
                                      (if (member r '(l r s e))
                                        r
                                        'l)))
                               (let ((v1 (ensure-dra-rel (dipole-point-relation a (list bsx bsy))))
                                     (v2 (ensure-dra-rel (dipole-point-relation a (list bex bey))))
                                     (v3 (ensure-dra-rel (dipole-point-relation b (list asx asy))))
                                     (v4 (ensure-dra-rel (dipole-point-relation b (list aex aey)))))
                                 (intern (format nil "~a~a~a~a" v1 v2 v3 v4)))))))

    ;;(external-lib "libdipole.dylib" "dipole_qualify_24")
    :algebraic-specification (
        (s?s?  ((1 ((sax 1))) = (1 ((sbx 1))))
               ((1 ((say 1))) = (1 ((sby 1)))))
        (?se?  ((1 ((sax 1))) = (1 ((ebx 1))))
               ((1 ((say 1))) = (1 ((eby 1)))))
        (e??s  ((1 ((eax 1))) = (1 ((sbx 1))))
               ((1 ((eay 1))) = (1 ((sby 1)))))
        (?e?e  ((1 ((eax 1))) = (1 ((ebx 1))))
               ((1 ((eay 1))) = (1 ((eby 1)))))
        (l???  ( 0 > (-1 ((sax 1)(eay 1))) ( 1 ((sax 1)(sby 1)))
                     ( 1 ((say 1)(eax 1))) (-1 ((say 1)(sbx 1)))
                     (-1 ((eax 1)(sby 1))) ( 1 ((eay 1)(sbx 1)))))
        (?l??  ( 0 > (-1 ((sax 1)(eay 1))) ( 1 ((sax 1)(eby 1)))
                     ( 1 ((say 1)(eax 1))) (-1 ((say 1)(ebx 1)))
                     (-1 ((eax 1)(eby 1))) ( 1 ((eay 1)(ebx 1)))))
        (??l?  ( 0 > (-1 ((sax 1)(sby 1))) ( 1 ((sax 1)(eby 1)))
                     ( 1 ((say 1)(sbx 1))) (-1 ((say 1)(ebx 1)))
                     (-1 ((sbx 1)(eby 1))) ( 1 ((sby 1)(ebx 1)))))
        (???l  ( 0 > (-1 ((eax 1)(sby 1))) ( 1 ((eax 1)(eby 1)))
                     ( 1 ((eay 1)(sbx 1))) (-1 ((eay 1)(ebx 1)))
                     (-1 ((sbx 1)(eby 1))) ( 1 ((sby 1)(ebx 1)))))
        (r???  ( 0 < (-1 ((sax 1)(eay 1))) ( 1 ((sax 1)(sby 1)))
                     ( 1 ((say 1)(eax 1))) (-1 ((say 1)(sbx 1)))
                     (-1 ((eax 1)(sby 1))) ( 1 ((eay 1)(sbx 1)))))
        (?r??  ( 0 < (-1 ((sax 1)(eay 1))) ( 1 ((sax 1)(eby 1)))
                     ( 1 ((say 1)(eax 1))) (-1 ((say 1)(ebx 1)))
                     (-1 ((eax 1)(eby 1))) ( 1 ((eay 1)(ebx 1)))))
        (??r?  ( 0 < (-1 ((sax 1)(sby 1))) ( 1 ((sax 1)(eby 1)))
                     ( 1 ((say 1)(sbx 1))) (-1 ((say 1)(ebx 1)))
                     (-1 ((sbx 1)(eby 1))) ( 1 ((sby 1)(ebx 1)))))
        (???r  ( 0 < (-1 ((eax 1)(sby 1))) ( 1 ((eax 1)(eby 1)))
                     ( 1 ((eay 1)(sbx 1))) (-1 ((eay 1)(ebx 1)))
                     (-1 ((sbx 1)(eby 1))) ( 1 ((sby 1)(ebx 1)))))
    )
    :base-relations (
        rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll
        ells errs lere rele slsr srsl lsel rser sese eses
    )
    :converse-operation (
        (rrrr rrrr)
        (rrrl rlrr)
        (rrlr lrrr)
        (rrll llrr)
        (rlrr rrrl)
        (rllr lrrl)
        (rlll llrl)
        (lrrr rrlr)
        (lrrl rllr)
        (lrll lllr)
        (llrr rrll)
        (llrl rlll)
        (lllr lrll)
        (llll llll)
        (ells lsel)
        (errs rser)
        (lere rele)
        (rele lere)
        (slsr srsl)
        (srsl slsr)
        (lsel ells)
        (rser errs)
        (sese sese)
        (eses eses)
    )
    :composition-operation (
        ( rrrr rrrr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( rrrr rrrl ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( rrrr rrlr ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( rrrr rrll ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( rrrr rlrr ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( rrrr rllr ( rrrr rrrl rrll rlrr rlll lrrr lrrl lrll errs srsl ))
        ( rrrr rlll ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( rrrr lrrr ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( rrrr lrrl ( rrrr rrlr rrll rlrr rllr rlll lrrr lrll rele rser ))
        ( rrrr lrll ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( rrrr llrr ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( rrrr llrl ( rrrr rrlr rrll lrrr lrll llrr llll ))
        ( rrrr lllr ( rrrr rrrl rrll rlrr rlll llrr llll ))
        ( rrrr llll ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( rrrr ells ( rrrr rrrl rrll rlrr rlll ))
        ( rrrr errs ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( rrrr lere ( rrrr rrlr rrll lrrr lrll ))
        ( rrrr rele ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( rrrr slsr ( rrrr rrrl rrll rlrr rlll ))
        ( rrrr srsl ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( rrrr lsel ( rrrr rrlr rrll lrrr lrll ))
        ( rrrr rser ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( rrrr sese ( rrrr ))
        ( rrrr eses ( rrll ))
        ( rrrl rrrr ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( rrrl rrrl ( rrrr rrrl rrlr rlrr rllr llrr lllr slsr rser ))
        ( rrrl rrlr ( rrrl rrlr rrll lrrl lrll llrl llll srsl lsel ))
        ( rrrl rrll ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( rrrl rlrr ( rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr lere rele slsr srsl sese ))
        ( rrrl rllr ( rrrl rrlr rrll rllr rlll lrrl lrll rele srsl ))
        ( rrrl rlll ( rrrl rrlr rrll rllr rlll lrrl lrll rele srsl ))
        ( rrrl lrrr ( rrrr rrrl rrlr rlrr rllr lrrr lrrl errs rser ))
        ( rrrl lrrl ( rrrr rrrl rrlr rlrr rllr lrrr lrrl errs rser ))
        ( rrrl lrll ( rrrr rrrl rrlr rlrr rllr rlll lrrr lrrl lrll llrl lllr llll ells errs lsel rser eses ))
        ( rrrl llrr ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( rrrl llrl ( rrrr rrrl rrlr lrrr lrrl llrr llrl errs lere ))
        ( rrrl lllr ( rrrl rrlr rrll rllr rlll lllr llll ells rele ))
        ( rrrl llll ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( rrrl ells ( rrrl rrlr rrll rllr rlll rele ))
        ( rrrl errs ( rrrr rrrl rrlr rlrr rllr rser ))
        ( rrrl lere ( rrrr rrrl rrlr lrrr lrrl errs ))
        ( rrrl rele ( rrrl rrlr rrll lrrl lrll srsl ))
        ( rrrl slsr ( rrrl rrlr rrll rllr rlll rele ))
        ( rrrl srsl ( rrrr rrrl rrlr rlrr rllr rser ))
        ( rrrl lsel ( rrrr rrrl rrlr lrrr lrrl errs ))
        ( rrrl rser ( rrrl rrlr rrll lrrl lrll srsl ))
        ( rrrl sese ( rrrl ))
        ( rrrl eses ( rrlr ))
        ( rrlr rrrr ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( rrlr rrrl ( rrrl rrlr rrll rllr rlll lllr llll ells rele ))
        ( rrlr rrlr ( rrrr rrrl rrlr lrrr lrrl llrr llrl errs lere ))
        ( rrlr rrll ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( rrlr rlrr ( rrrr rrrl rrlr rlrr rllr lrrr lrrl errs rser ))
        ( rrlr rllr ( rrrr rrrl rrlr rlrr rllr lrrr lrrl errs rser ))
        ( rrlr rlll ( rrrr rrrl rrlr rlrr rllr rlll lrrr lrrl lrll llrl lllr llll ells errs lsel rser eses ))
        ( rrlr lrrr ( rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr lere rele slsr srsl sese ))
        ( rrlr lrrl ( rrrl rrlr rrll rllr rlll lrrl lrll rele srsl ))
        ( rrlr lrll ( rrrl rrlr rrll rllr rlll lrrl lrll rele srsl ))
        ( rrlr llrr ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( rrlr llrl ( rrrl rrlr rrll lrrl lrll llrl llll srsl lsel ))
        ( rrlr lllr ( rrrr rrrl rrlr rlrr rllr llrr lllr slsr rser ))
        ( rrlr llll ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( rrlr ells ( rrrr rrrl rrlr rlrr rllr rser ))
        ( rrlr errs ( rrrl rrlr rrll rllr rlll rele ))
        ( rrlr lere ( rrrl rrlr rrll lrrl lrll srsl ))
        ( rrlr rele ( rrrr rrrl rrlr lrrr lrrl errs ))
        ( rrlr slsr ( rrrr rrrl rrlr rlrr rllr rser ))
        ( rrlr srsl ( rrrl rrlr rrll rllr rlll rele ))
        ( rrlr lsel ( rrrl rrlr rrll lrrl lrll srsl ))
        ( rrlr rser ( rrrr rrrl rrlr lrrr lrrl errs ))
        ( rrlr sese ( rrlr ))
        ( rrlr eses ( rrrl ))
        ( rrll rrrr ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( rrll rrrl ( rrrr rrrl rrll rlrr rlll llrr llll ))
        ( rrll rrlr ( rrrr rrlr rrll lrrr lrll llrr llll ))
        ( rrll rrll ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( rrll rlrr ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( rrll rllr ( rrrr rrlr rrll rlrr rllr rlll lrrr lrll rele rser ))
        ( rrll rlll ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( rrll lrrr ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( rrll lrrl ( rrrr rrrl rrll rlrr rlll lrrr lrrl lrll errs srsl ))
        ( rrll lrll ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( rrll llrr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( rrll llrl ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( rrll lllr ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( rrll llll ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( rrll ells ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( rrll errs ( rrrr rrrl rrll rlrr rlll ))
        ( rrll lere ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( rrll rele ( rrrr rrlr rrll lrrr lrll ))
        ( rrll slsr ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( rrll srsl ( rrrr rrrl rrll rlrr rlll ))
        ( rrll lsel ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( rrll rser ( rrrr rrlr rrll lrrr lrll ))
        ( rrll sese ( rrll ))
        ( rrll eses ( rrrr ))
        ( rlrr rrrr ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( rlrr rrrl ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( rlrr rrlr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( rlrr rrll ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( rlrr rlrr ( rrrr rrrl rrll rlrr lrrr lrrl lrll errs srsl ))
        ( rlrr rllr ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( rlrr rlll ( rlrr rllr rlll lrll llrr lllr llll ells slsr ))
        ( rlrr lrrr ( rlrr lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( rlrr lrrl ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( rlrr lrll ( rrrr rrlr rrll rlrr rllr rlll lrll rele rser ))
        ( rlrr llrr ( rrrr rrrl rrll rlrr llrr llrl llll ))
        ( rlrr llrl ( rrrr rrlr rrll rlrr lrll llrr llrl llll ))
        ( rlrr lllr ( rrrr rrrl rrll rlrr lrll llrr lllr llll ))
        ( rlrr llll ( rrrr rrlr rrll lrll llrr lllr llll ))
        ( rlrr ells ( lrll llrr lllr llll ))
        ( rlrr errs ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( rlrr lere ( rlrr llrr llrl llll ))
        ( rlrr rele ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( rlrr slsr ( rrrr rrrl rrll rlrr ))
        ( rlrr srsl ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( rlrr lsel ( rrrr rrlr rrll lrll ))
        ( rlrr rser ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( rlrr sese ( rlrr ))
        ( rlrr eses ( lrll ))
        ( rllr rrrr ( rrrr rrrl rrlr lrrr lrrl llrr llrl lllr errs lere ))
        ( rllr rrrl ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( rllr rrlr ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( rllr rrll ( rrrl rrlr rrll rllr rlll llrl lllr llll ells rele ))
        ( rllr rlrr ( rrrr rrrl rrlr rlrr rllr lrrr lrrl errs rser ))
        ( rllr rllr ( rrrr rrrl rrlr rlrr rllr rlll lrrr lrrl lrll llrl lllr llll ells errs lsel rser eses ))
        ( rllr rlll ( rllr rlll lrrl lrll llrl lllr llll ells lsel ))
        ( rllr lrrr ( rlrr rllr lrrr lrrl llrr llrl lllr lere slsr ))
        ( rllr lrrl ( rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr lere rele slsr srsl sese ))
        ( rllr lrll ( rrrl rrlr rrll rllr rlll lrrl lrll rele srsl ))
        ( rllr llrr ( rrrr rrrl rrlr rlrr rllr llrr llrl lllr slsr rser ))
        ( rllr llrl ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( rllr lllr ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( rllr llll ( rrrl rrlr rrll lrrl lrll llrl lllr llll srsl lsel ))
        ( rllr ells ( lrrl lrll llrl lllr llll lsel ))
        ( rllr errs ( lrrr lrrl llrr llrl lllr lere ))
        ( rllr lere ( rlrr rllr llrr llrl lllr slsr ))
        ( rllr rele ( rllr rlll llrl lllr llll ells ))
        ( rllr slsr ( rrrr rrrl rrlr rlrr rllr rser ))
        ( rllr srsl ( rrrl rrlr rrll rllr rlll rele ))
        ( rllr lsel ( rrrl rrlr rrll lrrl lrll srsl ))
        ( rllr rser ( rrrr rrrl rrlr lrrr lrrl errs ))
        ( rllr sese ( rllr ))
        ( rllr eses ( lrrl ))
        ( rlll rrrr ( rrrr rrlr rrll lrrr llrr lllr llll ))
        ( rlll rrrl ( rrrr rrrl rrll rlll lrrr llrr lllr llll ))
        ( rlll rrlr ( rrrr rrlr rrll rlll lrrr llrr llrl llll ))
        ( rlll rrll ( rrrr rrrl rrll rlll llrr llrl llll ))
        ( rlll rlrr ( rrrr rrlr rrll rlrr rllr rlll lrrr rele rser ))
        ( rlll rllr ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( rlll rlll ( rlll lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( rlll lrrr ( rlrr rllr rlll lrrr llrr lllr llll ells slsr ))
        ( rlll lrrl ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( rlll lrll ( rrrr rrrl rrll rlll lrrr lrrl lrll errs srsl ))
        ( rlll llrr ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( rlll llrl ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( rlll lllr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( rlll llll ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( rlll ells ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( rlll errs ( lrrr llrr lllr llll ))
        ( rlll lere ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( rlll rele ( rlll llrr llrl llll ))
        ( rlll slsr ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( rlll srsl ( rrrr rrrl rrll rlll ))
        ( rlll lsel ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( rlll rser ( rrrr rrlr rrll lrrr ))
        ( rlll sese ( rlll ))
        ( rlll eses ( lrrr ))
        ( lrrr rrrr ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( lrrr rrrl ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( lrrr rrlr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( lrrr rrll ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( lrrr rlrr ( rlrr rllr rlll lrrr llrr lllr llll ells slsr ))
        ( lrrr rllr ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( lrrr rlll ( rrrr rrrl rrll rlll lrrr lrrl lrll errs srsl ))
        ( lrrr lrrr ( rrrr rrlr rrll rlrr rllr rlll lrrr rele rser ))
        ( lrrr lrrl ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( lrrr lrll ( rlll lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( lrrr llrr ( rrrr rrlr rrll lrrr llrr lllr llll ))
        ( lrrr llrl ( rrrr rrlr rrll rlll lrrr llrr llrl llll ))
        ( lrrr lllr ( rrrr rrrl rrll rlll lrrr llrr lllr llll ))
        ( lrrr llll ( rrrr rrrl rrll rlll llrr llrl llll ))
        ( lrrr ells ( rrrr rrrl rrll rlll ))
        ( lrrr errs ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( lrrr lere ( rrrr rrlr rrll lrrr ))
        ( lrrr rele ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( lrrr slsr ( lrrr llrr lllr llll ))
        ( lrrr srsl ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( lrrr lsel ( rlll llrr llrl llll ))
        ( lrrr rser ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( lrrr sese ( lrrr ))
        ( lrrr eses ( rlll ))
        ( lrrl rrrr ( rrrr rrrl rrlr rlrr rllr llrr llrl lllr slsr rser ))
        ( lrrl rrrl ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( lrrl rrlr ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( lrrl rrll ( rrrl rrlr rrll lrrl lrll llrl lllr llll srsl lsel ))
        ( lrrl rlrr ( rlrr rllr lrrr lrrl llrr llrl lllr lere slsr ))
        ( lrrl rllr ( rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr lere rele slsr srsl sese ))
        ( lrrl rlll ( rrrl rrlr rrll rllr rlll lrrl lrll rele srsl ))
        ( lrrl lrrr ( rrrr rrrl rrlr rlrr rllr lrrr lrrl errs rser ))
        ( lrrl lrrl ( rrrr rrrl rrlr rlrr rllr rlll lrrr lrrl lrll llrl lllr llll ells errs lsel rser eses ))
        ( lrrl lrll ( rllr rlll lrrl lrll llrl lllr llll ells lsel ))
        ( lrrl llrr ( rrrr rrrl rrlr lrrr lrrl llrr llrl lllr errs lere ))
        ( lrrl llrl ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( lrrl lllr ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( lrrl llll ( rrrl rrlr rrll rllr rlll llrl lllr llll ells rele ))
        ( lrrl ells ( rrrl rrlr rrll rllr rlll rele ))
        ( lrrl errs ( rrrr rrrl rrlr rlrr rllr rser ))
        ( lrrl lere ( rrrr rrrl rrlr lrrr lrrl errs ))
        ( lrrl rele ( rrrl rrlr rrll lrrl lrll srsl ))
        ( lrrl slsr ( lrrr lrrl llrr llrl lllr lere ))
        ( lrrl srsl ( lrrl lrll llrl lllr llll lsel ))
        ( lrrl lsel ( rllr rlll llrl lllr llll ells ))
        ( lrrl rser ( rlrr rllr llrr llrl lllr slsr ))
        ( lrrl sese ( lrrl ))
        ( lrrl eses ( rllr ))
        ( lrll rrrr ( rrrr rrrl rrll rlrr llrr llrl llll ))
        ( lrll rrrl ( rrrr rrrl rrll rlrr lrll llrr lllr llll ))
        ( lrll rrlr ( rrrr rrlr rrll rlrr lrll llrr llrl llll ))
        ( lrll rrll ( rrrr rrlr rrll lrll llrr lllr llll ))
        ( lrll rlrr ( rlrr lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( lrll rllr ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( lrll rlll ( rrrr rrlr rrll rlrr rllr rlll lrll rele rser ))
        ( lrll lrrr ( rrrr rrrl rrll rlrr lrrr lrrl lrll errs srsl ))
        ( lrll lrrl ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( lrll lrll ( rlrr rllr rlll lrll llrr lllr llll ells slsr ))
        ( lrll llrr ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( lrll llrl ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( lrll lllr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( lrll llll ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( lrll ells ( rrrr rrlr rrll rlrr rllr rlll rele rser ))
        ( lrll errs ( rrrr rrrl rrll rlrr ))
        ( lrll lere ( rrrr rrrl rrll lrrr lrrl lrll errs srsl ))
        ( lrll rele ( rrrr rrlr rrll lrll ))
        ( lrll slsr ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( lrll srsl ( lrll llrr lllr llll ))
        ( lrll lsel ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( lrll rser ( rlrr llrr llrl llll ))
        ( lrll sese ( lrll ))
        ( lrll eses ( rlrr ))
        ( llrr rrrr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( llrr rrrl ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( llrr rrlr ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( llrr rrll ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( llrr rlrr ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( llrr rllr ( rlrr rllr rlll lrrr lrll llrr lllr llll ells slsr ))
        ( llrr rlll ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( llrr lrrr ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( llrr lrrl ( rlrr rlll lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( llrr lrll ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( llrr llrr ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( llrr llrl ( rrrr rrll rlrr rlll llrr llrl llll ))
        ( llrr lllr ( rrrr rrll lrrr lrll llrr lllr llll ))
        ( llrr llll ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( llrr ells ( lrrr lrll llrr lllr llll ))
        ( llrr errs ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( llrr lere ( rlrr rlll llrr llrl llll ))
        ( llrr rele ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( llrr slsr ( lrrr lrll llrr lllr llll ))
        ( llrr srsl ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( llrr lsel ( rlrr rlll llrr llrl llll ))
        ( llrr rser ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( llrr sese ( llrr ))
        ( llrr eses ( llll ))
        ( llrl rrrr ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( llrl rrrl ( rrrl rrll lrrl lrll llrl lllr llll srsl lsel ))
        ( llrl rrlr ( rrrr rrlr rlrr rllr llrr llrl lllr slsr rser ))
        ( llrl rrll ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( llrl rlrr ( rlrr rllr lrrr lrrl llrr llrl lllr lere slsr ))
        ( llrl rllr ( rlrr rllr lrrr lrrl llrr llrl lllr lere slsr ))
        ( llrl rlll ( rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr lere rele slsr srsl sese ))
        ( llrl lrrr ( rrrr rrrl rrlr rlrr rllr rlll lrrr lrrl lrll llrl lllr llll ells errs lsel rser eses ))
        ( llrl lrrl ( rllr rlll lrrl lrll llrl lllr llll ells lsel ))
        ( llrl lrll ( rllr rlll lrrl lrll llrl lllr llll ells lsel ))
        ( llrl llrr ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( llrl llrl ( rrlr rrll rllr rlll llrl lllr llll ells rele ))
        ( llrl lllr ( rrrr rrrl lrrr lrrl llrr llrl lllr errs lere ))
        ( llrl llll ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( llrl ells ( lrrr lrrl llrr llrl lllr lere ))
        ( llrl errs ( lrrl lrll llrl lllr llll lsel ))
        ( llrl lere ( rllr rlll llrl lllr llll ells ))
        ( llrl rele ( rlrr rllr llrr llrl lllr slsr ))
        ( llrl slsr ( lrrr lrrl llrr llrl lllr lere ))
        ( llrl srsl ( lrrl lrll llrl lllr llll lsel ))
        ( llrl lsel ( rllr rlll llrl lllr llll ells ))
        ( llrl rser ( rlrr rllr llrr llrl lllr slsr ))
        ( llrl sese ( llrl ))
        ( llrl eses ( lllr ))
        ( lllr rrrr ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( lllr rrrl ( rrrr rrrl lrrr lrrl llrr llrl lllr errs lere ))
        ( lllr rrlr ( rrlr rrll rllr rlll llrl lllr llll ells rele ))
        ( lllr rrll ( rrrr rrrl rrlr rrll rllr rlll lrrr lrrl llrr llrl lllr llll ells errs lere rele ))
        ( lllr rlrr ( rrrr rrrl rrlr rlrr rllr rlll lrrr lrrl lrll llrl lllr llll ells errs lsel rser eses ))
        ( lllr rllr ( rllr rlll lrrl lrll llrl lllr llll ells lsel ))
        ( lllr rlll ( rllr rlll lrrl lrll llrl lllr llll ells lsel ))
        ( lllr lrrr ( rlrr rllr lrrr lrrl llrr llrl lllr lere slsr ))
        ( lllr lrrl ( rlrr rllr lrrr lrrl llrr llrl lllr lere slsr ))
        ( lllr lrll ( rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr lere rele slsr srsl sese ))
        ( lllr llrr ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( lllr llrl ( rrrr rrlr rlrr rllr llrr llrl lllr slsr rser ))
        ( lllr lllr ( rrrl rrll lrrl lrll llrl lllr llll srsl lsel ))
        ( lllr llll ( rrrr rrrl rrlr rrll rlrr rllr lrrl lrll llrr llrl lllr llll slsr srsl lsel rser ))
        ( lllr ells ( lrrl lrll llrl lllr llll lsel ))
        ( lllr errs ( lrrr lrrl llrr llrl lllr lere ))
        ( lllr lere ( rlrr rllr llrr llrl lllr slsr ))
        ( lllr rele ( rllr rlll llrl lllr llll ells ))
        ( lllr slsr ( lrrl lrll llrl lllr llll lsel ))
        ( lllr srsl ( lrrr lrrl llrr llrl lllr lere ))
        ( lllr lsel ( rlrr rllr llrr llrl lllr slsr ))
        ( lllr rser ( rllr rlll llrl lllr llll ells ))
        ( lllr sese ( lllr ))
        ( lllr eses ( llrl ))
        ( llll rrrr ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( llll rrrl ( rrrr rrll lrrr lrll llrr lllr llll ))
        ( llll rrlr ( rrrr rrll rlrr rlll llrr llrl llll ))
        ( llll rrll ( rrrr rrrl rrlr rrll rlrr rlll lrrr lrll llrr llrl lllr llll ))
        ( llll rlrr ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( llll rllr ( rlrr rlll lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( llll rlll ( rrrr rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl llll lere rele lsel rser ))
        ( llll lrrr ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( llll lrrl ( rlrr rllr rlll lrrr lrll llrr lllr llll ells slsr ))
        ( llll lrll ( rrrr rrrl rrll rlrr rllr rlll lrrr lrrl lrll llrr lllr llll ells errs slsr srsl ))
        ( llll llrr ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser eses ))
        ( llll llrl ( rrrr rrlr rrll rlrr rllr rlll llrr lllr llll ells rele slsr rser ))
        ( llll lllr ( rrrr rrrl rrll lrrr lrrl lrll llrr llrl llll errs lere srsl lsel ))
        ( llll llll ( rrrr rrrl rrlr rrll rlrr rllr rlll lrrr lrrl lrll llrr llrl lllr llll ells errs lere rele slsr srsl lsel rser sese ))
        ( llll ells ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( llll errs ( lrrr lrll llrr lllr llll ))
        ( llll lere ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( llll rele ( rlrr rlll llrr llrl llll ))
        ( llll slsr ( lrrr lrrl lrll llrr llrl llll lere lsel ))
        ( llll srsl ( lrrr lrll llrr lllr llll ))
        ( llll lsel ( rlrr rllr rlll llrr lllr llll ells slsr ))
        ( llll rser ( rlrr rlll llrr llrl llll ))
        ( llll sese ( llll ))
        ( llll eses ( llrr ))
        ( ells rrrr ( rrrr rrlr lrrr llrr lllr ))
        ( ells rrrl ( rrrr lrrr llrr lllr ))
        ( ells rrlr ( rrll rlll llrl llll ))
        ( ells rrll ( rrrl rrll rlll llrl llll ))
        ( ells rlrr ( rrrr rrlr rlrr rllr lrrr rser ))
        ( ells rllr ( rlll lrrl lrll llrl llll lsel ))
        ( ells rlll ( rlll lrrl lrll llrl llll lsel ))
        ( ells lrrr ( rlrr rllr lrrr llrr lllr slsr ))
        ( ells lrrl ( rlrr rllr lrrr llrr lllr slsr ))
        ( ells lrll ( rrrl rrll rlll lrrl lrll srsl ))
        ( ells llrr ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( ells llrl ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( ells lllr ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( ells llll ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( ells ells ( lrrl lrll llrl llll lsel ))
        ( ells errs ( lrrr llrr lllr ))
        ( ells lere ( rlrr rllr llrr lllr slsr ))
        ( ells rele ( rlll llrl llll ))
        ( ells slsr ( ells errs eses ))
        ( ells srsl ( ells errs ))
        ( ells lsel ( lere rele sese ))
        ( ells rser ( lere rele ))
        ( ells sese ( ells ))
        ( ells eses ( lere ))
        ( errs rrrr ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( errs rrrl ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( errs rrlr ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( errs rrll ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( errs rlrr ( rlrr rllr lrrr llrr lllr slsr ))
        ( errs rllr ( rrrl rrll rlll lrrl lrll srsl ))
        ( errs rlll ( rrrl rrll rlll lrrl lrll srsl ))
        ( errs lrrr ( rrrr rrlr rlrr rllr lrrr rser ))
        ( errs lrrl ( rrrr rrlr rlrr rllr lrrr rser ))
        ( errs lrll ( rlll lrrl lrll llrl llll lsel ))
        ( errs llrr ( rrrr rrlr lrrr llrr lllr ))
        ( errs llrl ( rrrr rrlr lrrr llrr ))
        ( errs lllr ( rrrl rrll rlll llll ))
        ( errs llll ( rrrl rrll rlll llrl llll ))
        ( errs ells ( rrrl rrll rlll ))
        ( errs errs ( rrrr rrlr rlrr rllr rser ))
        ( errs lere ( rrrr rrlr lrrr ))
        ( errs rele ( rrrl rrll lrrl lrll srsl ))
        ( errs slsr ( ells errs ))
        ( errs srsl ( ells errs eses ))
        ( errs lsel ( lere rele ))
        ( errs rser ( lere rele sese ))
        ( errs sese ( errs ))
        ( errs eses ( rele ))
        ( lere rrrr ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( lere rrrl ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( lere rrlr ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( lere rrll ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( lere rlrr ( rlrr rllr lrrr llrr lllr slsr ))
        ( lere rllr ( rlrr rllr lrrr llrr lllr slsr ))
        ( lere rlll ( rrrl rrll rlll lrrl lrll srsl ))
        ( lere lrrr ( rrrr rrlr rlrr rllr lrrr rser ))
        ( lere lrrl ( rlll lrrl lrll llrl llll lsel ))
        ( lere lrll ( rlll lrrl lrll llrl llll lsel ))
        ( lere llrr ( rrrr rrlr lrrr llrr lllr ))
        ( lere llrl ( rrll rlll llrl llll ))
        ( lere lllr ( rrrr lrrr llrr lllr ))
        ( lere llll ( rrrl rrll rlll llrl llll ))
        ( lere ells ( ells errs ))
        ( lere errs ( ells errs eses ))
        ( lere lere ( lere rele ))
        ( lere rele ( lere rele sese ))
        ( lere slsr ( lrrr llrr lllr ))
        ( lere srsl ( lrrl lrll llrl llll lsel ))
        ( lere lsel ( rlll llrl llll ))
        ( lere rser ( rlrr rllr llrr lllr slsr ))
        ( lere sese ( lere ))
        ( lere eses ( ells ))
        ( rele rrrr ( rrrr rrlr lrrr llrr lllr ))
        ( rele rrrl ( rrrl rrll rlll llll ))
        ( rele rrlr ( rrrr rrlr lrrr llrr ))
        ( rele rrll ( rrrl rrll rlll llrl llll ))
        ( rele rlrr ( rrrr rrlr rlrr rllr lrrr rser ))
        ( rele rllr ( rrrr rrlr rlrr rllr lrrr rser ))
        ( rele rlll ( rlll lrrl lrll llrl llll lsel ))
        ( rele lrrr ( rlrr rllr lrrr llrr lllr slsr ))
        ( rele lrrl ( rrrl rrll rlll lrrl lrll srsl ))
        ( rele lrll ( rrrl rrll rlll lrrl lrll srsl ))
        ( rele llrr ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( rele llrl ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( rele lllr ( rrrr rrlr rlrr rllr llrr lllr slsr rser ))
        ( rele llll ( rrrl rrll lrrl lrll llrl llll srsl lsel ))
        ( rele ells ( ells errs eses ))
        ( rele errs ( ells errs ))
        ( rele lere ( lere rele sese ))
        ( rele rele ( lere rele ))
        ( rele slsr ( rrrr rrlr rlrr rllr rser ))
        ( rele srsl ( rrrl rrll rlll ))
        ( rele lsel ( rrrl rrll lrrl lrll srsl ))
        ( rele rser ( rrrr rrlr lrrr ))
        ( rele sese ( rele ))
        ( rele eses ( errs ))
        ( slsr rrrr ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( slsr rrrl ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( slsr rrlr ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( slsr rrll ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( slsr rlrr ( rrrr rrrl rlrr lrrr lrrl errs ))
        ( slsr rllr ( rllr rlll lrll lllr llll ells ))
        ( slsr rlll ( rllr rlll lrll lllr llll ells ))
        ( slsr lrrr ( rlrr lrrr lrrl llrr llrl lere ))
        ( slsr lrrl ( rlrr lrrr lrrl llrr llrl lere ))
        ( slsr lrll ( rrlr rrll rllr rlll lrll rele ))
        ( slsr llrr ( rrrr rrrl rlrr llrr llrl ))
        ( slsr llrl ( rrrr rlrr llrr llrl ))
        ( slsr lllr ( rrll lrll lllr llll ))
        ( slsr llll ( rrlr rrll lrll lllr llll ))
        ( slsr ells ( lrll lllr llll ))
        ( slsr errs ( lrrr lrrl llrr llrl lere ))
        ( slsr lere ( rlrr llrr llrl ))
        ( slsr rele ( rllr rlll lllr llll ells ))
        ( slsr slsr ( slsr srsl ))
        ( slsr srsl ( slsr srsl sese ))
        ( slsr lsel ( lsel rser ))
        ( slsr rser ( lsel rser eses ))
        ( slsr sese ( slsr ))
        ( slsr eses ( lsel ))
        ( srsl rrrr ( rrrr rrrl rlrr llrr llrl ))
        ( srsl rrrl ( rrrr rrrl rlrr llrr ))
        ( srsl rrlr ( rrlr rrll lrll llll ))
        ( srsl rrll ( rrlr rrll lrll lllr llll ))
        ( srsl rlrr ( rlrr lrrr lrrl llrr llrl lere ))
        ( srsl rllr ( rrlr rrll rllr rlll lrll rele ))
        ( srsl rlll ( rrlr rrll rllr rlll lrll rele ))
        ( srsl lrrr ( rrrr rrrl rlrr lrrr lrrl errs ))
        ( srsl lrrl ( rrrr rrrl rlrr lrrr lrrl errs ))
        ( srsl lrll ( rllr rlll lrll lllr llll ells ))
        ( srsl llrr ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( srsl llrl ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( srsl lllr ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( srsl llll ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( srsl ells ( rrlr rrll rllr rlll rele ))
        ( srsl errs ( rrrr rrrl rlrr ))
        ( srsl lere ( rrrr rrrl lrrr lrrl errs ))
        ( srsl rele ( rrlr rrll lrll ))
        ( srsl slsr ( slsr srsl sese ))
        ( srsl srsl ( slsr srsl ))
        ( srsl lsel ( lsel rser eses ))
        ( srsl rser ( lsel rser ))
        ( srsl sese ( srsl ))
        ( srsl eses ( rser ))
        ( lsel rrrr ( rrrr rrrl rlrr llrr llrl ))
        ( lsel rrrl ( rrll lrll lllr llll ))
        ( lsel rrlr ( rrrr rlrr llrr llrl ))
        ( lsel rrll ( rrlr rrll lrll lllr llll ))
        ( lsel rlrr ( rlrr lrrr lrrl llrr llrl lere ))
        ( lsel rllr ( rlrr lrrr lrrl llrr llrl lere ))
        ( lsel rlll ( rrlr rrll rllr rlll lrll rele ))
        ( lsel lrrr ( rrrr rrrl rlrr lrrr lrrl errs ))
        ( lsel lrrl ( rllr rlll lrll lllr llll ells ))
        ( lsel lrll ( rllr rlll lrll lllr llll ells ))
        ( lsel llrr ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( lsel llrl ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( lsel lllr ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( lsel llll ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( lsel ells ( slsr srsl sese ))
        ( lsel errs ( slsr srsl ))
        ( lsel lere ( lsel rser eses ))
        ( lsel rele ( lsel rser ))
        ( lsel slsr ( lrrr lrrl llrr llrl lere ))
        ( lsel srsl ( lrll lllr llll ))
        ( lsel lsel ( rllr rlll lllr llll ells ))
        ( lsel rser ( rlrr llrr llrl ))
        ( lsel sese ( lsel ))
        ( lsel eses ( slsr ))
        ( rser rrrr ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( rser rrrl ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( rser rrlr ( rrrr rrrl lrrr lrrl llrr llrl errs lere ))
        ( rser rrll ( rrlr rrll rllr rlll lllr llll ells rele ))
        ( rser rlrr ( rrrr rrrl rlrr lrrr lrrl errs ))
        ( rser rllr ( rrrr rrrl rlrr lrrr lrrl errs ))
        ( rser rlll ( rllr rlll lrll lllr llll ells ))
        ( rser lrrr ( rlrr lrrr lrrl llrr llrl lere ))
        ( rser lrrl ( rrlr rrll rllr rlll lrll rele ))
        ( rser lrll ( rrlr rrll rllr rlll lrll rele ))
        ( rser llrr ( rrrr rrrl rlrr llrr llrl ))
        ( rser llrl ( rrlr rrll lrll llll ))
        ( rser lllr ( rrrr rrrl rlrr llrr ))
        ( rser llll ( rrlr rrll lrll lllr llll ))
        ( rser ells ( slsr srsl ))
        ( rser errs ( slsr srsl sese ))
        ( rser lere ( lsel rser ))
        ( rser rele ( lsel rser eses ))
        ( rser slsr ( rrrr rrrl rlrr ))
        ( rser srsl ( rrlr rrll rllr rlll rele ))
        ( rser lsel ( rrlr rrll lrll ))
        ( rser rser ( rrrr rrrl lrrr lrrl errs ))
        ( rser sese ( rser ))
        ( rser eses ( srsl ))
        ( sese rrrr ( rrrr ))
        ( sese rrrl ( rrrl ))
        ( sese rrlr ( rrlr ))
        ( sese rrll ( rrll ))
        ( sese rlrr ( rlrr ))
        ( sese rllr ( rllr ))
        ( sese rlll ( rlll ))
        ( sese lrrr ( lrrr ))
        ( sese lrrl ( lrrl ))
        ( sese lrll ( lrll ))
        ( sese llrr ( llrr ))
        ( sese llrl ( llrl ))
        ( sese lllr ( lllr ))
        ( sese llll ( llll ))
        ( sese ells ( ells ))
        ( sese errs ( errs ))
        ( sese lere ( lere ))
        ( sese rele ( rele ))
        ( sese slsr ( slsr ))
        ( sese srsl ( srsl ))
        ( sese lsel ( lsel ))
        ( sese rser ( rser ))
        ( sese sese ( sese ))
        ( sese eses ( eses ))
        ( eses rrrr ( llrr ))
        ( eses rrrl ( lllr ))
        ( eses rrlr ( llrl ))
        ( eses rrll ( llll ))
        ( eses rlrr ( lrrr ))
        ( eses rllr ( lrrl ))
        ( eses rlll ( lrll ))
        ( eses lrrr ( rlrr ))
        ( eses lrrl ( rllr ))
        ( eses lrll ( rlll ))
        ( eses llrr ( rrrr ))
        ( eses llrl ( rrlr ))
        ( eses lllr ( rrrl ))
        ( eses llll ( rrll ))
        ( eses ells ( srsl ))
        ( eses errs ( slsr ))
        ( eses lere ( rser ))
        ( eses rele ( lsel ))
        ( eses slsr ( errs ))
        ( eses srsl ( ells ))
        ( eses lsel ( rele ))
        ( eses rser ( lere ))
        ( eses sese ( eses ))
        ( eses eses ( sese ))
    )
    :cnhs (
        ( (default)
	  ( ( rrrr ( errs rser eses ))
	    ( rrrl ())
	    ( rrlr ())
	    ( rrll ())
	    ( rlrr ())
	    ( rllr ())
	    ( rlll ())
	    ( lrrr ())
	    ( lrrl ())
	    ( lrll ())
	    ( llrr ())
	    ( llrl ())
	    ( lllr ())
	    ( llll ())
	    ( ells ())
	    ( errs ())
	    ( lere ())
	    ( rele ())
	    ( slsr ())
	    ( srsl ())
	    ( lsel ())
	    ( rser ())
	    ( sese ())
	    ( eses ())
          )
        )
    )
)
