;;;
;;; QTC-B11: Qualitative Trajectory Calculus Basic 1D Level 1 with 9 base relations
;;;

(def-calculus "QTC-B11: Qualitative Trajectory Calculus Basic 1D Level 1 with 9 base relations"
  :arity :binary
  ;;:qualifier (external-lib "libqtc.dylib" "qualify_qtc_b11")
  :basis-entity :dipole ;; 1D point resp. 1D interval
  :identity-relation OO
  :converse-operation ( ( -- -- )
			( -O O- )
			( -+ +- )
			( O- -O )
			( OO OO )
			( O+ +O )
			( +- -+ )
			( +O O+ )
			( ++ ++ ))
  
  :base-relations (-- -O -+ O- OO O+ +- +O ++)
  :composition-operation (
			  (-- -- ( -+ +- ))
			  (-- -O ( -O +O )) 
			  (-- -+ ( -- ++ )) 
			  (-- O- ( )) 
			  (-- OO ( )) 
			  (-- O+ ( )) 
			  (-- +- ( -- )) 
			  (-- +O ( -O )) 
			  (-- ++ ( -+ )) 

			  (-O -- ( )) 
			  (-O -O ( )) 
			  (-O -+ ( )) 
			  (-O O- ( -- -+ +- )) 
			  (-O OO ( -O +O )) 
			  (-O O+ ( -- -+ ++)) 
			  (-O +- ( )) 
			  (-O +O ( )) 
			  (-O ++ ( )) 

			  (-+ -- ( -- )) 
			  (-+ -O ( -O )) 
			  (-+ -+ ( -+ )) 
			  (-+ O- ( )) 
			  (-+ OO ( )) 
			  (-+ O+ ( )) 
			  (-+ +- ( -+ +- )) 
			  (-+ +O ( -O +O )) 
			  (-+ ++ ( -- ++ )) 
			  
			  (O- -- ( O- O+ )) 
			  (O- -O ( OO )) 
			  (O- -+ ( O- O+ )) 
			  (O- O- ( )) 
			  (O- OO ( )) 
			  (O- O+ ( )) 
			  (O- +- ( O- )) 
			  (O- +O ( OO )) 
			  (O- ++ ( O+ )) 

			  (OO -- ( )) 
			  (OO -O ( )) 
			  (OO -+ ( )) 
			  (OO O- ( O- O+ )) 
			  (OO OO ( OO )) 
			  (OO O+ ( O- O+ )) 
			  (OO +- ( )) 
			  (OO +O ( )) 
			  (OO ++ ( )) 

			  (O+ -- ( O- )) 
			  (O+ -O ( OO )) 
			  (O+ -+ ( O+ )) 
			  (O+ O- ( )) 
			  (O+ OO ( )) 
			  (O+ O+ ( )) 
			  (O+ +- ( O- O+ )) 
			  (O+ +O ( OO )) 
			  (O+ ++ ( O- O+)) 

			  (+- -- ( -- ++ )) 
			  (+- -O ( -O +O )) 
			  (+- -+ ( -+ +- )) 
			  (+- O- ( )) 
			  (+- OO ( )) 
			  (+- O+ ( )) 
			  (+- +- ( +- )) 
			  (+- +O ( +O )) 
			  (+- ++ ( ++ )) 

			  (+O -- ( )) 
			  (+O -O ( )) 
			  (+O -+ ( )) 
			  (+O O- ( -- +- ++ )) 
			  (+O OO ( +O -O )) 
			  (+O O+ ( -+ +- ++ )) 
			  (+O +- ( )) 
			  (+O +O ( )) 
			  (+O ++ ( )) 

			  (++ -- ( +- )) 
			  (++ -O ( +O )) 
			  (++ -+ ( ++ )) 
			  (++ O- ( )) 
			  (++ OO ( )) 
			  (++ O+ ( )) 
			  (++ +- ( -- ++ )) 
			  (++ +O ( -O +O )) 
			  (++ ++ ( -+ +- )) 
			  )
  )


